l_french:
 is_your_child_desc: "Est votre enfant"
 is_your_close_family_desc: "Est de votre proche famille"
 is_your_house_desc: "Est de votre Maison"
 landed_spouse_desc: "A un conjoint ayant des terres"
 landed_heir_desc: "A un héritier ayant des terres"
 has_many_good_relations_desc: "A beaucoup d’amis"
 has_many_bad_relations_desc: "A beaucoup de rivaux"
 part_of_feud_desc: "Participe à une querelle"
 high_diplomacy_desc: "A un haut niveau de diplomatie"
 high_martial_desc: "A un haut niveau de martialité"
 high_stewardship_desc: "A un haut niveau d’intendance"
 high_intrigue_desc: "A un haut niveau d’intrigue"
 high_learning_desc: "A un haut niveau d’érudition"
 high_prowess_desc: "A un haut niveau de prouesse"
 high_education_desc: "A un haut niveau d’éducation"
 more_beautiful_desc: "A une beauté supérieure à l’héritier"
 more_smart_desc: "A une intelligence supérieure à l’héritier"
 more_fit_desc: "Est plus en forme que l’héritier"
 more_strong_desc: "A plus de force que l’héritier"
 more_skillful_desc: "A plus d’aptitudes que l’héritier"
 has_nickname_desc: "A un surnom"
 more_famous_desc: "Plus célèbre que l’héritier"
 second_in_line_desc: "Deuxième de la ligne de succession"
 higher_title_desc: "Détient un titre plus élevé"
 new_liege_desc: "Serait sous l’autorité d’un autre seigneur lige"
 new_top_liege_desc: "Serait sous l’autorité d’un autre souverain"
 tall_claims_desc: "Détient des revendications importantes"
 pressed_claims_desc: "Détient des revendications appuyées"
 unpressed_claims_desc: "Détient des revendications non appuyées"
 inheritance_line_desc: "Dans la ligne de succession"
 has_interesting_story_desc: "A une histoire intéressante"
 child_of_destiny_desc: "Est un enfant du destin"
 virtues_interesting_desc: "A des traits vertueux"
 tourney_xp_desc: "[GetTrait('tourney_participant').GetName( GetNullCharacter )] expérimenté"
 reveler_xp_desc: "[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )] expérimenté"
 mystic_xp_desc: "[GetTrait('lifestyle_mystic').GetName( GetNullCharacter )] expérimenté"
 hunter_xp_desc: "[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )] expérimenté"
 blademaster_xp_desc: "[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )] expérimenté"
 traveler_xp_desc: "[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )] expérimenté"
 physician_xp_desc: "[GetTrait('lifestyle_physician').GetName( GetNullCharacter )] expérimenté"
 herbalist_xp_desc: "[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )] expérimenté"
 loyal_interesting_desc: "Est [GetTrait('loyal').GetName( GetNullCharacter )|l]"
 disloyal_interesting_desc: "Est [GetTrait('disloyal').GetName( GetNullCharacter )|l]"
 faith_warrior_interesting_desc: "Est un [GetTrait('faith_warrior').GetName( GetNullCharacter )|l]"
 blood_of_prophet_interesting_desc: "A le [GetTrait('blood_of_prophet').GetName( GetNullCharacter )|l]"
 varangian_interesting_desc: "Est un [GetTrait('varangian').GetName( GetNullCharacter )|l]"
 poet_interesting_desc: "Est un [GetTrait('lifestyle_poet').GetName( GetNullCharacter )|l]"
 peasant_leader_interesting_desc: "Est un [GetTrait('peasant_leader').GetName( GetNullCharacter )|l]"
 populist_leader_interesting_desc: "Est un [GetTrait('populist_leader').GetName( GetNullCharacter )|l]"
 berserker_interesting_desc: "Est un [GetTrait('berserker').GetName( GetNullCharacter )|l]"
 born_in_the_purple_interesting_desc: "Est [GetTrait('born_in_the_purple').GetName( GetNullCharacter )|l]"
 scaly_interesting_desc: "Est [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 albino_interesting_desc: "Est un [GetTrait('albino').GetName( GetNullCharacter )|l]"
 dwarf_interesting_desc: "Est un [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 giant_interesting_desc: "Est un [GetTrait('giant').GetName( GetNullCharacter )|l]"
 devoted_interesting_desc: "Est un [GetTrait('devoted').GetName( GetNullCharacter )|l]"
 pure_blooded_interesting_desc: "Est [GetTrait('pure_blooded').GetName( GetNullCharacter )|l]"
 crusader_king_interesting_desc: "Est un [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 disinherited_interesting_desc: "Est [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 blind_interesting_desc: "Est [GetTrait('blind').GetName( GetNullCharacter )|l]"
 is_diarch_interesting_desc: "Est un dyarque"
 ruler_in_foreign_lands_interesting_desc: "Est un dirigeant étranger"
 valiant_knight_interesting_desc: "Est un valeureux chevalier"
 sinful_bastard_interesting_desc: "Est un [GetTrait('bastard').GetName( GetNullCharacter )|l] pécheur"
 adventurer_interesting_desc: "Est un aventurier"
 liege_crusader_king_liege_lineage_interesting_desc: "Seigneur lige d’une lignée de [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 holy_site_steward_interesting_desc: "La capitale est un lieu saint"
 has_a_legend_interesting_desc: "A une légende"
 weak_hook_liege_interesting_desc: "A un hameçon faible contre le seigneur lige"
 strong_hook_liege_interesting_desc: "A un hameçon fort contre le seigneur lige"
 beloved_by_pope_interesting_desc: "Aimé par le Pape"
 head_of_faith_interesting_desc: "Est un chef de foi"
 stronger_than_liege_interesting_desc: "Plus fort que le seigneur lige"
 small_king_interesting_desc: "Est le dirigeant d’un petit royaume"
 can_feudalize_interesting_desc: "Peut se féodaliser"
 multiduke_interesting_desc: "Détient de nombreux duchés"
 legitimacy_interesting_desc: "Dirigeant extrêmement légitime"
 non_dominant_gender_ambitious_char_interesting_desc: "Est un personnage ambitieux de sexe non dominant"
 non_dominant_gender_ruler_interesting_desc: "Est un dirigeant de sexe non dominant"
 treacherous_schemer_interesting_desc: "Est un comploteur perfide"
 kind_hearted_diplomat_interesting_desc: "Est un diplomate au grand cœur"
 different_faith_interesting_desc: "D’une foi différente"
 greedy_steward_interesting_desc: "Est un intendant avide"
 brazen_commander_interesting_desc: "Est un commandant effronté"
 pious_theologian_interesting_desc: "Est un théologien pieux"
 salacious_seducer_interesting_desc: "Est un séducteur salace"
 high_skills_desc: "Les aptitudes sont très élevées"
 killed_a_lot_interesting_desc: "A tué plus de 10 personnes"
 has_both_good_and_bad_genetics_desc: "A à la fois de bons et de mauvais traits génétiques"
 good_genetics_desc: "Bons traits génétiques"
 bad_genetics_desc: "Mauvais traits génétiques"
 holds_rome_interesting_desc: "Détient [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Détient [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Détient [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Détient [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Détient [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Contrôle des bâtiments spéciaux"
 has_historical_artifacts_interesting_desc: "Possède des artefacts historiques uniques"
 underrepresented_faith_interesting_desc: "Est d’une foi sous-représentée"
 underrepresented_culture_interesting_desc: "Est d’une culture sous-représentée"
 outside_realm_desc: "Dirigeant indépendant"
 knows_many_secrets_interesting_desc: "Connaît de nombreux secrets"
 has_secrets_interesting_desc: "A des secrets"
 extremely_wealthy_interesting_desc: "Très riche"
 landless_heir_uninteresting_desc: "Héritier du titre sans terres"
 three_virtues_desc: "A trois vertus"
 three_sins_desc: "A trois péchés"
 skills_difficulty: "Des aptitudes"
 legitimacy_difficulty: "De la légitimité"
 virtuous_traits_difficulty: "A des traits vertueux"
 physique_good_3_difficulty: "Est [GetTrait('physique_good_3').GetName( GetNullCharacter )|l]"
 physique_good_2_difficulty: "Est [GetTrait('physique_good_2').GetName( GetNullCharacter )|l]"
 physique_good_1_difficulty: "Est [GetTrait('physique_good_1').GetName( GetNullCharacter )|l]"
 intellect_good_3_difficulty: "Est un [GetTrait('intellect_good_3').GetName( GetNullCharacter )|l]"
 intellect_good_2_difficulty: "Est [GetTrait('intellect_good_2').GetName( GetNullCharacter )|l]"
 intellect_good_1_difficulty: "Est [GetTrait('intellect_good_1').GetName( GetNullCharacter )|l]"
 beauty_good_3_difficulty: "Est [GetTrait('beauty_good_3').GetName( GetNullCharacter )|l]"
 beauty_good_2_difficulty: "Est [GetTrait('beauty_good_2').GetName( GetNullCharacter )|l]"
 beauty_good_1_difficulty: "A un [GetTrait('beauty_good_1').GetName( GetNullCharacter )|l]"
 shrewd_difficulty: "Use de la [GetTrait('shrewd').GetName( GetNullCharacter )|l]"
 strong_difficulty: "Use de la [GetTrait('strong').GetName( GetNullCharacter )|l]"
 sinful_traits_difficulty: "A des traits pécheurs"
 incapable_difficulty: "Est un [GetTrait('incapable').GetName( GetNullCharacter )|l]"
 leper_difficulty: "A la [GetTrait('leper').GetName( GetNullCharacter )|l]"
 maimed_difficulty: "Est [GetTrait('maimed').GetName( GetNullCharacter )|l]"
 inbred_difficulty: "A des liens de [GetTrait('inbred').GetName( GetNullCharacter )|l]"
 severely_wounded_difficulty: "Est grièvement blessé"
 disinherited_difficulty: "Est [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 sickly_difficulty: "Est un [GetTrait('sickly').GetName( GetNullCharacter )|l]"
 poxed_difficulty: "A la [GetTrait('great_pox').GetName( GetNullCharacter )|l]"
 blind_difficulty: "Est [GetTrait('blind').GetName( GetNullCharacter )|l]"
 infirm_difficulty: "Est [GetTrait('infirm').GetName( GetNullCharacter )|l]"
 eunuch_difficulty: "Est un [GetTrait('eunuch_1').GetName( GetNullCharacter )|l]"
 lunatic_difficulty: "A des dispositions [GetTrait('lunatic').GetName( GetNullCharacter )|l]"
 murderer_difficulty: "Est un [GetTrait('murderer').GetName( GetNullCharacter )|l]"
 excommunicated_difficulty: "Est excommunié"
 bleeder_difficulty: "Est un [GetTrait('bleeder').GetName( GetNullCharacter )|l]"
 physique_bad_3_difficulty: "Est [GetTrait('physique_bad_3').GetName( GetNullCharacter )|l]"
 physique_bad_2_difficulty: "Est [GetTrait('physique_bad_2').GetName( GetNullCharacter )|l]"
 physique_bad_1_difficulty: "Est [GetTrait('physique_bad_1').GetName( GetNullCharacter )|l]"
 intellect_bad_3_difficulty: "Est un [GetTrait('intellect_bad_3').GetName( GetNullCharacter )|l]"
 intellect_bad_2_difficulty: "Est [GetTrait('intellect_bad_2').GetName( GetNullCharacter )|l]"
 intellect_bad_1_difficulty: "Est [GetTrait('intellect_bad_1').GetName( GetNullCharacter )|l]"
 beauty_bad_3_difficulty: "Est [GetTrait('beauty_bad_3').GetName( GetNullCharacter )|l]"
 beauty_bad_2_difficulty: "Est d’une [GetTrait('beauty_bad_2').GetName( GetNullCharacter )|l]"
 beauty_bad_1_difficulty: "Est [GetTrait('beauty_bad_1').GetName( GetNullCharacter )|l]"
 dull_difficulty: "Est [GetTrait('dull').GetName( GetNullCharacter )|l]"
 weak_difficulty: "Use de [GetTrait('weak').GetName( GetNullCharacter )|l]"
 sodomite_difficulty: "Est un [GetTrait('sodomite').GetName( GetNullCharacter )|l]"
 incestuous_difficulty: "Est [GetTrait('incestuous').GetName( GetNullCharacter )|l]"
 fornicator_difficulty: "Est un [GetTrait('fornicator').GetName( GetNullCharacter )|l]"
 adulterer_difficulty: "Est un [GetTrait('adulterer').GetName( GetNullCharacter )|l]"
 cannibal_difficulty: "Est un [GetTrait('cannibal').GetName( GetNullCharacter )|l]"
 witch_difficulty: "Est un [GetTrait('witch').GetName( GetNullCharacter )|l]"
 kinslayer_difficulty: "Est un [GetTrait('kinslayer_1').GetName( GetNullCharacter )|l]"
 flagellant_difficulty: "Use de l’[GetTrait('flagellant').GetName( GetNullCharacter )|l]"
 improvident_difficulty: "Est [GetTrait('improvident').GetName( GetNullCharacter )|l]"
 profligate_difficulty: "Est [GetTrait('profligate').GetName( GetNullCharacter )|l]"
 disfigured_difficulty: "Est [GetTrait('disfigured').GetName( GetNullCharacter )|l]"
 drunkard_difficulty: "Est un [GetTrait('drunkard').GetName( GetNullCharacter )|l]"
 possessed_difficulty: "A des états [GetTrait('possessed').GetName( GetNullCharacter )|l]"
 depressed_difficulty: "A des états [GetTrait('depressed').GetName( GetNullCharacter )|l]"
 infertile_difficulty: "Est [GetTrait('infertile').GetName( GetNullCharacter )|l]"
 spindly_difficulty: "Est [GetTrait('spindly').GetName( GetNullCharacter )|l]"
 paranoid_difficulty: "Est [GetTrait('paranoid').GetName( GetNullCharacter )|l]"
 gout_difficulty: "Est [GetTrait('gout_ridden').GetName( GetNullCharacter )|l]"
 wheezing_difficulty: "[GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "Est [GetTrait('craven').GetName( GetNullCharacter )|l]"
 shy_difficulty: "Est [GetTrait('shy').GetName( GetNullCharacter )|l]"
 decadent_difficulty: "Est visé par une [GetTrait('decadent').GetName( GetNullCharacter )|l]"
 denounced_difficulty: "Est [GetTrait('denounced').GetName( GetNullCharacter )|l]"
 bastard_difficulty: "Est un [GetTrait('bastard').GetName( GetNullCharacter )|l]"
 weak_heritage_difficulty: "A un héritage modeste"
 comfort_eater_difficulty: "Est un [GetTrait('comfort_eater').GetName( GetNullCharacter )|l]"
 inappetetic_difficulty: "Est [GetTrait('inappetetic').GetName( GetNullCharacter )|l]"
 reclusive_difficulty: "Est [GetTrait('reclusive').GetName( GetNullCharacter )|l]"
 irritable_difficulty: "Est [GetTrait('irritable').GetName( GetNullCharacter )|l]"
 rakish_difficulty: "Est [GetTrait('rakish').GetName( GetNullCharacter )|l]"
 hashishiyah_difficulty: "Est un [GetTrait('hashishiyah').GetName( GetNullCharacter )|l]"
 celibate_difficulty: "Est en [GetTrait('celibate').GetName( GetNullCharacter )|l]"
 lovers_pox_difficulty: "A la [GetTrait('lovers_pox').GetName( GetNullCharacter )|l]"
 wounded_difficulty: "Est [GetTrait('wounded_1').GetName( GetNullCharacter )|l]"
 albino_difficulty: "Est un [GetTrait('albino').GetName( GetNullCharacter )|l]"
 lisping_difficulty: "Est un [GetTrait('lisping').GetName( GetNullCharacter )|l]"
 stuttering_difficulty: "Souffre de [GetTrait('stuttering').GetName( GetNullCharacter )|l]"
 giant_difficulty: "Est un [GetTrait('giant').GetName( GetNullCharacter )|l]"
 scaly_difficulty: "Est [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 clubfooted_difficulty: "A un [GetTrait('clubfooted').GetName( GetNullCharacter )|l]"
 dwarf_difficulty: "Est un [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 hunchbacked_difficulty: "Est [GetTrait('hunchbacked').GetName( GetNullCharacter )|l]"
 lazy_difficulty: "Est [GetTrait('lazy').GetName( GetNullCharacter )|l]"
 gluttonous_difficulty: "Est [GetTrait('gluttonous').GetName( GetNullCharacter )|l]"
 deviant_difficulty: "Est un [GetTrait('deviant').GetName( GetNullCharacter )|l]"
 at_war_difficulty: "En guerre"
 losing_war_difficulty: "Guerres perdues"
 faction_difficulty: "Ciblé par des factions puissantes"
 powerful_neighbors_difficulty: "Dirigeants voisins puissants"
 military_difficulty: "Puissance militaire"
 rivals_difficulty: "A des rivaux"
 primary_heir_wrong_dynasty_difficulty: "Héritier principal de la mauvaise dynastie"
 children_wrong_dynasty_difficulty: "Enfants de la mauvaise dynastie"
 hostile_faith_liege_difficulty: "Seigneur lige d’une foi hostile"
 nonpreferred_gender_difficulty: "Sexe non préféré par la foi"
 wrong_lineality_difficulty: "Mauvaise linéarité dans le mariage"
 stress_level_difficulty: "Niveau de stress élevé"
 gold_difficulty: "Richesse excessive"
 debt_level_difficulty: "Niveau d’endettement élevé"
 is_ill_difficulty: "Souffre d’une maladie débilitante"
 imprisoned_difficulty: "En prison"
 elder_difficulty: "Âge avancé"
 poor_health_difficulty: "Mauvaise santé"
 is_a_vassal_difficulty: "Est un vassal"
 non_adult_difficulty: "Enfant"
 weak_domain_difficulty: "Domaine faible"
 unlanded_difficulty: "Ne détient aucun titre"
 character_difficulty_text: "Difficulté : [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "Analyse de la difficulté"
 choose_destiny_header_text: "Choisissez un nouveau destin"
 will_become_adventurer: "Deviendra un [GetGovernment('landless_adventurer_government').GetName|l]"
 character_interest_breakdown_header: "Aspects intéressants"
 different_government_desc: "A un gouvernement différent"
 opposite_struggle_faction_desc: "Faction opposée dans une lutte"
