l_french:
 SETTING_DEBUG_SAVES: "Nombre de sauvegardes de débogage"
 SETTING_TUTORIAL: "Didacticiel"
 SETTING_DISABLED_HINTS: "Conseils désactivés"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Délai de l’infobulle"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant l’apparition des infobulles."
 SETTING_TOOLTIP_UNLOCK_TIME: "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant que les infobulles soient déverrouillées."
 SETTING_TOOLTIP_LOCK_TIME: "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu’une autre infobulle est déjà ouverte."
 #Audio
 SETTING_Sound_Effects: "Tous les effets sonores"
 SETTING_Sound_Effects_TOOLTIP: "#T Volume des effets sonores\n#!Règle le volume de tous les effets sonores."
 SETTING_Ambience: "Ambiance"
 SETTING_Ambience_TOOLTIP: "#T Volume d’ambiance\n#!Règle le volume des sons d’ambiance."
 SETTING_TOOLTIP_MODE: "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nDéfinit la façon dont les infobulles « se verrouillent » et activent les infobulles dans les infobulles."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Selon la souris"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nLes infobulles sont automatiquement verrouillées jusqu’à ce que le curseur s’éloigne."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Selon l’action"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nAppuyer sur le #V bouton du milieu de la souris#! pour verrouiller ou déverrouiller les infobulles."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Selon le temps"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nLes infobulles sont verrouillées si le curseur ne bouge pas pendant un court instant. #weak (Paramètre par défaut)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Divers"
 SETTINGS_CATEGORY_TOOLTIPS: "Infobulles"
 SETTINGS_CATEGORY_SFX: "Effets sonores spécifiques"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Général"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Contrôles de carte"
 SETTINGS_CATEGORY_SAVE_GAMES: "Sauvegardes"
 SETTINGS_CATEGORY_LANGUAGE: "Langue"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avancé – général"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Avancé – carte"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Avancé – personnages"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portraits"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Variété"
 SETTINGS_CATEGORY_MULTIPLAYER: "Multijoueur"
 SETTINGS_CATEGORY_MAP: "Carte"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Afficher les maladies et les blessures"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nDétermine si les graphismes des maladies et blessures sont visibles sur les portraits des personnages."
 SETTING_SHOW_NUDITY: "Afficher la nudité"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDétermine si les personnages peuvent apparaître nus."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Contenu téléchargeable"
 SETTING_SHOW_CONTENT_SOURCE: "Afficher le contenu téléchargeable de l’événement"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nDéfinit si les événements affichent le DLC dont ils proviennent."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Panoramique de la Cour royale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDétermine si la caméra de la Cour royale doit effectuer un léger panoramique sur votre cour lorsqu’elle est inutilisée.\n\nSi les personnages animés sont désactivés, ce paramètre n’a aucun effet."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Transitions de la Cour royale"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDétermine si la caméra de la Cour royale doit se déplacer doucement vers un nouvel emplacement.\n\nSi les personnages animés sont désactivés, ce paramètre n’a aucun effet."
 NEVER: "Jamais"
 MONTHLY: "Chaque mois"
 HALFYEAR: "Tous les 6 mois"
 YEARLY: "Chaque année"
 FIVE_YEAR: "Tous les 5 ans"
 SETTINGS_CATEGORY_TUTORIAL: "Didacticiel"
 SETTING_REACTIVE_TUTORIAL: "Afficher les conseils personnalisés"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nDétermine si le jeu doit afficher des conseils qui réagissent à la façon dont vous jouez. Utile pour les nouveaux joueurs de Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Afficher les suggestions"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nDéfinit si le jeu doit régulièrement suggérer des choses à faire. C’est utile pour les joueurs découvrant Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Réinitialiser les conseils personnalisés#!\nLes conseils personnalisés vus précédemment réapparaîtront."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Réinitialiser les conseils personnalisés"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Voulez-vous vraiment réinitialiser les conseils personnalisés ?"
 SETTING_ADVANCED_SHADERS: "Effets de nuanceur avancés"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Effets de nuanceur avancés\n#!Cette option permettra des effets de nuanceur avancés.\n\nLe fait de le désactiver peut augmenter les performances au risque d’aggraver la qualité de certains effets (par exemple, le terrain et l’eau)"
 SETTING_WINTER_PARTICLE_EFFECTS: "Effets des particules d’hiver"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDétermine si les effets des particules sont visibles lorsque l’hiver est en cours dans une zone de la carte.\n\nLes désactiver peut améliorer les performances"
 SETTING_RESET_CAMERA_ROTATION: "Réinitialisation de la caméra"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDétermine si la caméra doit automatiquement rétablir sa position par défaut après avoir été tournée par l’utilisateur."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Inclinaison de la caméra en cas de zoom arrière"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nDétermine si la caméra doit s’incliner vers l’angle par défaut lors d’un zoom arrière."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Personnages d’arrière-plan"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDétermine si la Cour royale en 3D doit afficher des personnages d’arrière-plan moins importants."
 SETTING_MAP_HIGHLIGHT: "Mise en évidence du curseur"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nDétermine l’intensité de la mise en évidence du curseur sur la carte"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Mise en évidence du supérieur"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nDétermine quand le dirigeant indépendant d’un pays est mis en évidence lors de la sélection d’un pays."
 OPTION_ALWAYS: "Toujours"
 OPTION_TRIBUTARY_ONLY: "Tributaires uniquement"
 BASED_ON_ZOOM_LEVEL: "Dynamique"
 ALWAYS_HIDE: "Toujours masquer"
 ALWAYS_SHOW: "Toujours afficher"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Frontières côtières"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nCette option permettra de contrôler à quel moment les frontières des pays côtiers doivent être indiquées.\nSi $BASED_ON_ZOOM_LEVEL$ alors elles seront masquées au niveau de zoom détaillé.\n\nChoisir $ALWAYS_SHOW$ ou $ALWAYS_HIDE$ peut augmenter les performances, mais les frontières des pays côtiers ne se masquent plus dynamiquement."
 SETTINGS_DISCARD_CHANGES: "Annuler les modifications"
 SETTING_HUD_SKIN: "Thème HUD"
 hud_skin_auto: "Dynamique"
 default: "Par défaut"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nDéfinit le thème visuel de l’interface HUD – Interface utilisateur 2D affichée sur l’écran de jeu principal.\n\nSi $hud_skin_auto$ est sélectionné, le HUD change en fonction de la culture, de la foi et de la capitale du pays du joueur."
 SETTING_RICH_PRESENCE: "Statut en temps réel"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nAffichez des informations sur votre session de jeu en cours à vos amis si votre plateforme le prend en charge."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Pays nommés selon la dynastie"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nCertaines cultures nommeront leur titre principal d’après leur dynastie (par exemple : les Abbassides)."
 map_table_style_auto: "Dynamique"
 map_table_style_western: "Par défaut"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Style de table de carte"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nDéfinit le style visuel de la table de carte (la carte et l’environnement 3D affichés en cas de zoom arrière).\n\nSi $map_table_style_auto$ est sélectionné, un style de table de carte sera sélectionné en fonction du joueur actuel et de son personnage."
 SETTINGS_CATEGORY_STYLING: "Style de l’interface"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Graphisme des maladies"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nDéfinit si les effets de la maladie doivent être affichés sur la carte"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Graphismes de la légende"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nDéfinit si les effets de la légende doivent être affichés sur la carte"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Icônes de [raid|El] détaillées"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nDéfinit si la carte de [raid|El] doit afficher les icônes simplifiées ou détaillées\n\n#I En cas d’activation, maintenez Alt pour afficher toutes les propriétés avec du butin que vous pouvez [Concept('raid','piller')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Icônes de [Concept('barter', 'troc')|E] détaillées"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nDéfinit si la carte de [Concept('barter', 'troc')|E] doit afficher les icônes simplifiées ou détaillées\n\n#I En cas d’activation, maintenez Alt pour afficher toutes les propriétés avec du butin dans lesquelles vous pouvez faire un [Concept('barter', 'troc')|E].#!"
 SETTING_PAPER_MAP_STYLE: "Style de carte papier"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nDéfinit le style de carte affiché lorsque la carte est agrandie.\n\nSi $paper_map_style_auto$ est choisi, la carte papier suivra le $SETTING_MAP_TABLE_STYLE|l$."
 paper_map_style_auto: "Dynamique"
 paper_map_style_western: "Par défaut"
 paper_map_style_tgp: "All Under Heaven"
 SETTING_ADAPTIVE_FRAMERATE: "Fréquence d’images adaptative"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Réduit la fréquence de rafraîchissement de l’écran si la vitesse de mise à jour du jeu diminue afin d’améliorer les performances de jeu."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Ombre nuageuse"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nDétermine si les effets d’ombre des nuages doivent être affichés sur le terrain."
 SETTING_HAS_TREE_DITHERING_ENABLED: "Tramage des arbres"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nDétermine si des effets de tramage doivent être appliqués aux arbres afin d’adoucir les contours."
 SETTING_MAP_BRIGHTNESS: "Luminosité de la carte papier"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nDétermine l’intensité de la luminosité de la carte papier"
