l_german:
 is_your_child_desc: "Ist Euer Kind"
 is_your_close_family_desc: "Gehört zu Euren nahen Verwandtschaft"
 is_your_house_desc: "Gehört zu Eurem Haus"
 landed_spouse_desc: "Hat einen Ehepartner mit Landbesitz"
 landed_heir_desc: "Hat einen Erben mit Landbesitz"
 has_many_good_relations_desc: "Hat viele Freunde"
 has_many_bad_relations_desc: "Wird von Rivalen heimgesucht"
 part_of_feud_desc: "Teil einer Fehde"
 high_diplomacy_desc: "Hat hohe Diplomatie"
 high_martial_desc: "Hat hohe Kriegsführung"
 high_stewardship_desc: "Hat hohe Verwaltung"
 high_intrigue_desc: "Hat hohes Ränkespiel"
 high_learning_desc: "Hat hohe Bildung"
 high_prowess_desc: "Hat hohes Kampfgeschick"
 high_education_desc: "Ist hochgebildet"
 more_beautiful_desc: "Ist schöner als Erbe"
 more_smart_desc: "Ist klüger als Erbe"
 more_fit_desc: "Ist gesünder als Erbe"
 more_strong_desc: "Ist stärker als Erbe"
 more_skillful_desc: "Ist fähiger als Erbe"
 has_nickname_desc: "Hat einen Spitznamen"
 more_famous_desc: "Ist berühmter als Erbe"
 second_in_line_desc: "An zweiter Stelle in der Erbfolge"
 higher_title_desc: "Hält einen höheren Titel"
 new_liege_desc: "Stünde unter einem neuen Lehnsherrn"
 new_top_liege_desc: "Stünde unter einem neuen Obersten Lehnsherrn"
 tall_claims_desc: "Hält wichtige Ansprüche"
 pressed_claims_desc: "Hält durchgesetzte Ansprüche"
 unpressed_claims_desc: "Hält fallengelassene Ansprüche"
 inheritance_line_desc: "In der Erbfolge"
 has_interesting_story_desc: "Hat eine interessante Geschichte"
 child_of_destiny_desc: "Ist ein Schicksalskind"
 virtues_interesting_desc: "Hat tugendhafte Eigenschaften"
 tourney_xp_desc: "Erfahrener [GetTrait('tourney_participant').GetName(GetNullCharacter)]"
 reveler_xp_desc: "Erfahrener [GetTrait('lifestyle_reveler').GetName(GetNullCharacter)]"
 mystic_xp_desc: "Erfahrener [GetTrait('lifestyle_mystic').GetName(GetNullCharacter)]"
 hunter_xp_desc: "Erfahrener [GetTrait('lifestyle_hunter').GetName(GetNullCharacter)]"
 blademaster_xp_desc: "Erfahrener [GetTrait('lifestyle_blademaster').GetName(GetNullCharacter)]"
 traveler_xp_desc: "Erfahrener [GetTrait('lifestyle_traveler').GetName(GetNullCharacter)]"
 physician_xp_desc: "Erfahrener [GetTrait('lifestyle_physician').GetName(GetNullCharacter)]"
 herbalist_xp_desc: "Erfahrener [GetTrait('lifestyle_herbalist').GetName(GetNullCharacter)]"
 loyal_interesting_desc: "Ist [GetTrait('loyal').GetName(GetNullCharacter)|l]"
 disloyal_interesting_desc: "Ist [GetTrait('disloyal').GetName(GetNullCharacter)|l]"
 faith_warrior_interesting_desc: "Ist ein [GetTrait('faith_warrior').GetName(GetNullCharacter)]"
 blood_of_prophet_interesting_desc: "Hat das [GetTrait('blood_of_prophet').GetName(GetNullCharacter)]"
 varangian_interesting_desc: "Ist ein [GetTrait('varangian').GetName(GetNullCharacter)]"
 poet_interesting_desc: "Ist ein [GetTrait('lifestyle_poet').GetName(GetNullCharacter)]"
 peasant_leader_interesting_desc: "Ist ein [GetTrait('peasant_leader').GetName(GetNullCharacter)]"
 populist_leader_interesting_desc: "Ist ein [GetTrait('populist_leader').GetName(GetNullCharacter)]"
 berserker_interesting_desc: "Ist ein [GetTrait('berserker').GetName(GetNullCharacter)]"
 born_in_the_purple_interesting_desc: "Ist [GetTrait('born_in_the_purple').GetName(GetNullCharacter)]"
 scaly_interesting_desc: "Hat [GetTrait('scaly').GetName(GetNullCharacter)|l]e Haut"
 albino_interesting_desc: "Ist ein [GetTrait('albino').GetName(GetNullCharacter)]"
 dwarf_interesting_desc: "Ist ein [GetTrait('dwarf').GetName(GetNullCharacter)]"
 giant_interesting_desc: "Ist ein [GetTrait('giant').GetName(GetNullCharacter)]"
 devoted_interesting_desc: "Ist [GetTrait('devoted').GetName(GetNullCharacter)|l]"
 pure_blooded_interesting_desc: "Ist [GetTrait('pure_blooded').GetName(GetNullCharacter)|l]"
 crusader_king_interesting_desc: "Ist ein [GetTrait('crusader_king').GetName(GetNullCharacter)]"
 disinherited_interesting_desc: "Wurde [GetTrait('disinherited').GetName(GetNullCharacter)|l]"
 blind_interesting_desc: "Ist blind"
 is_diarch_interesting_desc: "Ist ein Diarch"
 ruler_in_foreign_lands_interesting_desc: "Ist ein Herrscher im Ausland"
 valiant_knight_interesting_desc: "Ist ein tapferer Ritter"
 sinful_bastard_interesting_desc: "Ist ein sündiger [GetTrait('bastard').GetName(GetNullCharacter)]"
 adventurer_interesting_desc: "Ist ein Abenteurer"
 liege_crusader_king_liege_lineage_interesting_desc: "Lehnsherr mit [GetTrait('crusader_king').GetName(GetNullCharacter)]-Abstammung"
 holy_site_steward_interesting_desc: "Hauptsitz ist eine Heilige Stätte"
 has_a_legend_interesting_desc: "Hat eine Legende"
 weak_hook_liege_interesting_desc: "Hat Schwaches Druckmittel gegen Lehnsherrn"
 strong_hook_liege_interesting_desc: "Hat Starkes Druckmittel gegen Lehnsherrn"
 beloved_by_pope_interesting_desc: "Geliebt vom Papst"
 head_of_faith_interesting_desc: "Ist ein Glaubensoberhaupt"
 stronger_than_liege_interesting_desc: "Stärker als Lehnsherr"
 small_king_interesting_desc: "Ist Herrscher eines Kleinkönigreichs"
 can_feudalize_interesting_desc: "Kann feudalisieren"
 multiduke_interesting_desc: "Hält zu viele Herzogtümer"
 legitimacy_interesting_desc: "Äußerst legitimer Herrscher"
 non_dominant_gender_ambitious_char_interesting_desc: "Ist ein ehrgeiziger Charakter vom nicht-dominanten Geschlecht"
 non_dominant_gender_ruler_interesting_desc: "Ist ein Herrscher vom nicht-dominanten Geschlecht"
 treacherous_schemer_interesting_desc: "Ist ein verräterischer Anstifter"
 kind_hearted_diplomat_interesting_desc: "Ist ein gutherziger Diplomat"
 different_faith_interesting_desc: "Von einem anderen Glauben"
 greedy_steward_interesting_desc: "Ist ein gieriger Verwalter"
 brazen_commander_interesting_desc: "Ist ein schamloser Befehlshaber"
 pious_theologian_interesting_desc: "Ist ein frommer Theologe"
 salacious_seducer_interesting_desc: "Ist ein lüsterner Verführer"
 high_skills_desc: "Werte sind sehr hoch"
 killed_a_lot_interesting_desc: "Hat mehr als 10 Menschen getötet"
 has_both_good_and_bad_genetics_desc: "Hat sowohl gute als auch schlechte vererbliche Eigenschaften"
 good_genetics_desc: "Gute vererbliche Eigenschaften"
 bad_genetics_desc: "Schlechte vererbliche Eigenschaften"
 holds_rome_interesting_desc: "Hält [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Hält [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Hält [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Hält [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Hält [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Kontrolliert Sondergebäude"
 has_historical_artifacts_interesting_desc: "Besitzt einzigartige historische Artefakte"
 underrepresented_faith_interesting_desc: "Gehört einem unterrepräsentierten Glauben an"
 underrepresented_culture_interesting_desc: "Gehört einer unterrepräsentierten Kultur an"
 outside_realm_desc: "Unabhängiger Herrscher"
 knows_many_secrets_interesting_desc: "Kennt viele Geheimnisse"
 has_secrets_interesting_desc: "Hat Geheimnisse"
 extremely_wealthy_interesting_desc: "Sehr reich"
 landless_heir_uninteresting_desc: "Titelerbe ohne Landbesitz"
 three_virtues_desc: "Hat drei Tugenden"
 three_sins_desc: "Hat drei Sünden"
 skills_difficulty: "Durch Werte"
 legitimacy_difficulty: "Durch Legitimität"
 virtuous_traits_difficulty: "Hat tugendhafte Eigenschaften"
 physique_good_3_difficulty: "Ist [GetTrait('physique_good_3').GetName(GetNullCharacter)|l]"
 physique_good_2_difficulty: "Ist [GetTrait('physique_good_2').GetName(GetNullCharacter)|l]"
 physique_good_1_difficulty: "Ist [GetTrait('physique_good_1').GetName(GetNullCharacter)|l]"
 intellect_good_3_difficulty: "Ist ein [GetTrait('intellect_good_3').GetName(GetNullCharacter)]"
 intellect_good_2_difficulty: "Ist [GetTrait('intellect_good_2').GetName(GetNullCharacter)|l]"
 intellect_good_1_difficulty: "Ist [GetTrait('intellect_good_1').GetName(GetNullCharacter)|l]"
 beauty_good_3_difficulty: "Ist [GetTrait('beauty_good_3').GetName(GetNullCharacter)|l]"
 beauty_good_2_difficulty: "Ist [GetTrait('beauty_good_2').GetName(GetNullCharacter)|l]"
 beauty_good_1_difficulty: "Ist [GetTrait('beauty_good_1').GetName(GetNullCharacter)|l]"
 shrewd_difficulty: "Ist [GetTrait('shrewd').GetName(GetNullCharacter)|l]"
 strong_difficulty: "Ist [GetTrait('strong').GetName(GetNullCharacter)|l]"
 sinful_traits_difficulty: "Hat sündhafte Eigenschaften"
 incapable_difficulty: "Ist [GetTrait('incapable').GetName(GetNullCharacter)|l]"
 leper_difficulty: "Ist [GetTrait('leper').GetName(GetNullCharacter)]"
 maimed_difficulty: "Ist [GetTrait('maimed').GetName(GetNullCharacter)|l]"
 inbred_difficulty: "Ist [GetTrait('inbred').GetName(GetNullCharacter)|l]"
 severely_wounded_difficulty: "Ist schwer verwundet"
 disinherited_difficulty: "Wurde [GetTrait('disinherited').GetName(GetNullCharacter)|l]"
 sickly_difficulty: "Ist [GetTrait('sickly').GetName(GetNullCharacter)|l]"
 poxed_difficulty: "Hat die [GetTrait('great_pox').GetName(GetNullCharacter)]"
 blind_difficulty: "Ist blind"
 infirm_difficulty: "Ist [GetTrait('infirm').GetName(GetNullCharacter)|l]"
 eunuch_difficulty: "Ist ein [GetTrait('eunuch_1').GetName(GetNullCharacter)]"
 lunatic_difficulty: "Ist ein [GetTrait('lunatic').GetName(GetNullCharacter)|l]"
 murderer_difficulty: "Ist ein [GetTrait('murderer').GetName(GetNullCharacter)]"
 excommunicated_difficulty: "Ist exkommuniziert"
 bleeder_difficulty: "Ist ein [GetTrait('bleeder').GetName(GetNullCharacter)]"
 physique_bad_3_difficulty: "Ist [GetTrait('physique_bad_3').GetName(GetNullCharacter)|l]"
 physique_bad_2_difficulty: "Ist [GetTrait('physique_bad_2').GetName(GetNullCharacter)|l]"
 physique_bad_1_difficulty: "Ist [GetTrait('physique_bad_1').GetName(GetNullCharacter)|l]"
 intellect_bad_3_difficulty: "Ist ein [GetTrait('intellect_bad_3').GetName(GetNullCharacter)]"
 intellect_bad_2_difficulty: "Ist [GetTrait('intellect_bad_2').GetName(GetNullCharacter)|l]"
 intellect_bad_1_difficulty: "Ist [GetTrait('intellect_bad_1').GetName(GetNullCharacter)|l]"
 beauty_bad_3_difficulty: "Ist [GetTrait('beauty_bad_3').GetName(GetNullCharacter)|l]"
 beauty_bad_2_difficulty: "Ist [GetTrait('beauty_bad_2').GetName(GetNullCharacter)|l]"
 beauty_bad_1_difficulty: "Ist [GetTrait('beauty_bad_1').GetName(GetNullCharacter)|l]"
 dull_difficulty: "Ist [GetTrait('dull').GetName(GetNullCharacter)|l]"
 weak_difficulty: "Ist [GetTrait('weak').GetName(GetNullCharacter)|l]"
 sodomite_difficulty: "Ist ein [GetTrait('sodomite').GetName(GetNullCharacter)]"
 incestuous_difficulty: "Ist [GetTrait('incestuous').GetName(GetNullCharacter)|l]"
 fornicator_difficulty: "Ist ein [GetTrait('fornicator').GetName(GetNullCharacter)]"
 adulterer_difficulty: "Ist ein [GetTrait('adulterer').GetName(GetNullCharacter)]"
 cannibal_difficulty: "Ist ein [GetTrait('cannibal').GetName(GetNullCharacter)]"
 witch_difficulty: "Ist eine [GetTrait('witch').GetName(GetNullCharacter)]"
 kinslayer_difficulty: "Ist ein [GetTrait('kinslayer_1').GetName(GetNullCharacter)]"
 flagellant_difficulty: "Ist ein [GetTrait('flagellant').GetName(GetNullCharacter)]"
 improvident_difficulty: "Ist [GetTrait('improvident').GetName(GetNullCharacter)|l]"
 profligate_difficulty: "Ist [GetTrait('profligate').GetName(GetNullCharacter)|l]"
 disfigured_difficulty: "Ist [GetTrait('disfigured').GetName(GetNullCharacter)|l]"
 drunkard_difficulty: "Ist ein [GetTrait('drunkard').GetName(GetNullCharacter)]"
 possessed_difficulty: "Ist [GetTrait('possessed').GetName(GetNullCharacter)|l]"
 depressed_difficulty: "Ist [GetTrait('depressed').GetName(GetNullCharacter)|l]"
 infertile_difficulty: "Ist [GetTrait('infertile').GetName(GetNullCharacter)|l]"
 spindly_difficulty: "Ist [GetTrait('spindly').GetName(GetNullCharacter)|l]"
 paranoid_difficulty: "Ist [GetTrait('paranoid').GetName(GetNullCharacter)|l]"
 gout_difficulty: "Ist [GetTrait('gout_ridden').GetName(GetNullCharacter)|l]"
 wheezing_difficulty: "Ist ein [GetTrait('wheezing').GetName(GetNullCharacter)]"
 craven_difficulty: "Ist [GetTrait('craven').GetName(GetNullCharacter)|l]"
 shy_difficulty: "Ist [GetTrait('shy').GetName(GetNullCharacter)|l]"
 decadent_difficulty: "Ist [GetTrait('decadent').GetName(GetNullCharacter)|l]"
 denounced_difficulty: "Ist [GetTrait('denounced').GetName(GetNullCharacter)|l]"
 bastard_difficulty: "Ist ein [GetTrait('bastard').GetName(GetNullCharacter)]"
 weak_heritage_difficulty: "Hat eine schwache Abstammung"
 comfort_eater_difficulty: "Ist ein [GetTrait('comfort_eater').GetName(GetNullCharacter)]"
 inappetetic_difficulty: "Ist [GetTrait('inappetetic').GetName(GetNullCharacter)|l]"
 reclusive_difficulty: "Ist [GetTrait('reclusive').GetName(GetNullCharacter)|l]"
 irritable_difficulty: "Ist [GetTrait('irritable').GetName(GetNullCharacter)|l]"
 rakish_difficulty: "Ist [GetTrait('rakish').GetName(GetNullCharacter)|l]"
 hashishiyah_difficulty: "Ist ein [GetTrait('hashishiyah').GetName(GetNullCharacter)]"
 celibate_difficulty: "Ist [GetTrait('celibate').GetName(GetNullCharacter)|l]"
 lovers_pox_difficulty: "Hat [GetTrait('lovers_pox').GetName(GetNullCharacter)]"
 wounded_difficulty: "Ist [GetTrait('wounded_1').GetName(GetNullCharacter)|l]"
 albino_difficulty: "Ist ein [GetTrait('albino').GetName(GetNullCharacter)]"
 lisping_difficulty: "Ist ein [GetTrait('lisping').GetName(GetNullCharacter)]"
 stuttering_difficulty: "Ist ein [GetTrait('stuttering').GetName(GetNullCharacter)]"
 giant_difficulty: "Ist ein [GetTrait('giant').GetName(GetNullCharacter)]"
 scaly_difficulty: "Ist [GetTrait('scaly').GetName(GetNullCharacter)|l]"
 clubfooted_difficulty: "Ist [GetTrait('clubfooted').GetName(GetNullCharacter)]"
 dwarf_difficulty: "Ist ein [GetTrait('dwarf').GetName(GetNullCharacter)]"
 hunchbacked_difficulty: "Ist [GetTrait('hunchbacked').GetName(GetNullCharacter)|l]"
 lazy_difficulty: "Ist [GetTrait('lazy').GetName(GetNullCharacter)|l]"
 gluttonous_difficulty: "Ist [GetTrait('gluttonous').GetName(GetNullCharacter)|l]"
 deviant_difficulty: "Ist ein [GetTrait('deviant').GetName(GetNullCharacter)]"
 at_war_difficulty: "Im Krieg"
 losing_war_difficulty: "Verliert Kriege"
 faction_difficulty: "Ziel mächtiger Fraktionen"
 powerful_neighbors_difficulty: "Mächtige benachbarte Herrscher"
 military_difficulty: "Militärische Stärke"
 rivals_difficulty: "Hat Rivalen"
 primary_heir_wrong_dynasty_difficulty: "Haupterbe von falscher Dynastie"
 children_wrong_dynasty_difficulty: "Kind von falscher Dynastie"
 hostile_faith_liege_difficulty: "Lehnsherr von feindlichem Glauben"
 nonpreferred_gender_difficulty: "Nicht-bevorzugtes Geschlecht im Glauben"
 wrong_lineality_difficulty: "Falsche Linie in Ehe"
 stress_level_difficulty: "Hohe Anspannungsstufe"
 gold_difficulty: "Übermäßiger Reichtum"
 debt_level_difficulty: "Hohe Schuldenstufe"
 is_ill_difficulty: "Leidet an lähmender Erkrankung"
 imprisoned_difficulty: "Eingekerkert"
 elder_difficulty: "Fortgeschrittenes Alter"
 poor_health_difficulty: "Schlechte Gesundheit"
 is_a_vassal_difficulty: "Ist ein Vasall"
 non_adult_difficulty: "Kind"
 weak_domain_difficulty: "Schwache Domäne"
 unlanded_difficulty: "Hält keine Titel"
 character_difficulty_text: "Schwierigkeit: [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "Schwierigkeitenauflistung"
 choose_destiny_header_text: "Wählt ein neues Schicksal"
 will_become_adventurer: "Wird [GetGovernment('landless_adventurer_government').GetName]"
 character_interest_breakdown_header: "Interessante Aspekte"
 different_government_desc: "Hat eine andere Regierung"
 opposite_struggle_faction_desc: "Gegnerische Fraktion in einem Ringen"
