l_german:
 SETTING_DEBUG_SAVES: "Anzahl an Debug-Saves"
 SETTING_TUTORIAL: "Tutorial"
 SETTING_DISABLED_HINTS: "Deaktivierte Tipps"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Tooltip-Verzögerung"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, bis Tooltips erscheinen."
 SETTING_TOOLTIP_UNLOCK_TIME: "Freischaltungsverzögerung"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips freigeschaltet werden."
 SETTING_TOOLTIP_LOCK_TIME: "Verriegelungsverzögerung"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Geöffnet-Geschlossen-Verzögerung"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden, während ein anderer Tooltip geöffnet ist."
 #Audio
 SETTING_Sound_Effects: "Alle Soundeffekte"
 SETTING_Sound_Effects_TOOLTIP: "#T Soundeffekte-Lautstärke\n#!Legt die Lautstärke aller Soundeffekte fest."
 SETTING_Ambience: "Umgebung"
 SETTING_Ambience_TOOLTIP: "#T Umgebungslautstärke\n#!Legt die Lautstärke der Umgebungs-Atmo fest."
 SETTING_TOOLTIP_MODE: "Tooltip-Modus"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nLegt fest, wie Tooltips „einrasten“ und erlaubt so Tooltips innerhalb von Tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Maustendenz"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips rasten automatisch an Ort und Stelle ein, bis sich der Mauszeiger wegbewegt."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Aktions-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nBenutzt die #V Mittlere Maustaste#!, um Tooltips ein- und ausrasten zu lassen."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Timer-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips bleiben an Ort und Stelle eingerastet, solange sich der Mauszeiger eine kleine Weile nicht bewegt. #weak (Standardeinstellung.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Diverses"
 SETTINGS_CATEGORY_TOOLTIPS: "Tooltips"
 SETTINGS_CATEGORY_SFX: "Spezifische Soundeffekte"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Allgemein"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Kartensteuerung"
 SETTINGS_CATEGORY_SAVE_GAMES: "Spielstände"
 SETTINGS_CATEGORY_LANGUAGE: "Sprache"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Fortgeschritten – Allgemein"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Fortgeschritten – Karte"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Fortgeschritten – Charaktere"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Porträts"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Weltereignisse"
 SETTINGS_CATEGORY_MULTIPLAYER: "Mehrspieler"
 SETTINGS_CATEGORY_MAP: "Karte"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Verletzungen und Krankheiten darstellen"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nLegt fest, ob deutliche Verletzungen und Krankheiten bei Charakterporträts dargestellt werden."
 SETTING_SHOW_NUDITY: "Nacktheit anzeigen"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nLegt fest, ob Charaktere nackt gezeigt werden können."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Herunterladbarer Inhalt"
 SETTING_SHOW_CONTENT_SOURCE: "DLC des Ereignisses anzeigen"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nLegt fest, ob Ereignisse anzeigen, aus welchem DLC sie stammen."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Leerlauf-Schwenk bei Hofe"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nLegt fest, ob die Kamera im Königshof sanft über den Thronsaal schwenken soll, wenn sie unbeschäftigt ist.\n\nWenn animierte Charaktere abgeschaltet sind, hat diese Einstellung keine Auswirkungen."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Sanfte Königshof-Übergänge"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nLegt fest, ob die Kamera sich im Königshof sanft zum neuen Ort bewegen soll.\n\nWenn animierte Charaktere abgeschaltet sind, hat diese Einstellung keine Auswirkungen."
 NEVER: "Nie"
 MONTHLY: "Jeden Monat"
 HALFYEAR: "Alle 6 Monate"
 YEARLY: "Jedes Jahr"
 FIVE_YEAR: "Alle 5 Jahre"
 SETTINGS_CATEGORY_TUTORIAL: "Tutorial"
 SETTING_REACTIVE_TUTORIAL: "Reaktive Ratschläge anzeigen"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nLegt fest, ob das Spiel Ratschläge im Stil eines Tutorials in Reaktion auf Euer Handeln gibt. Nützlich für Spieler, die neu bei Crusader Kings III sind."
 SETTING_SHOW_SUGGESTIONS: "Vorschläge anzeigen"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nLegt fest, ob das Spiel in gewissen Abständen Vorschläge machen soll. Nützlich für Spieler, die neu bei Crusader Kings III sind."
 RESET_REACTIVE_ADVICE: "Reaktive Ratschläge zurücksetzen"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Reaktive Ratschläge zurücksetzen#!\nSchon gesehene Reaktive Ratschläge tauchen nur einmal auf."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Reaktive Ratschläge zurücksetzen"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Bist du sicher, dass du die reaktiven Ratschläge zurücksetzen willst?"
 SETTING_ADVANCED_SHADERS: "Advanced-Shader-Effekte"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Advanced-Shader-Effekte\n#!Diese Auswahl aktiviert Advanced-Shader-Effekte.\n\nDas Abschalten kann die Leistung verbessern. Manche Effekte (beispielsweise Gelände und Wasser) können allerdings schlechter aussehen."
 SETTING_WINTER_PARTICLE_EFFECTS: "Winter-Partikeleffekte"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nLegt fest, ob in manchen Teilen der Karte während des Winters Partikeleffekte angezeigt werden oder nicht.\n\nDas Abschalten kann die Leistung verbessern."
 SETTING_RESET_CAMERA_ROTATION: "Zurücksetzen der Kameradrehung"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nBestimmt, ob die Kamera automatisch in die Standardausgangsposition zurückkehrt, nachdem der Spieler sie gedreht hat"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Kameraneigung beim Herauszoomen"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nBestimmt, ob sich die Kamera beim Herauszoomen in Richtung der Standardneigung bewegen soll."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Hofszenen-Statisten"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nLegt fest, ob die 3-D-Szene am Königshof weniger wichtiger Hintergrundcharaktere zeigen sollte oder nicht."
 SETTING_MAP_HIGHLIGHT: "Kartenanzeiger-Hervorhebung"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nBestimmt, wie sehr der Zeiger auf der Karte hervorgehoben wird"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Karten-Oberherrhervorhebung"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nBestimmt, ob der oberste Suzerän eines Reichs hervorgehoben wird, wenn man ein Reich auswählt."
 OPTION_ALWAYS: "Immer"
 OPTION_TRIBUTARY_ONLY: "Nur Tributzahler"
 BASED_ON_ZOOM_LEVEL: "Dynamisch"
 ALWAYS_HIDE: "Immer verbergen"
 ALWAYS_SHOW: "Immer anzeigen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Küstengrenzen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nDiese Auswahl steuert, wann Reichsgrenzen an den Küsten angezeigt werden sollen.\nBei „$BASED_ON_ZOOM_LEVEL$“ werden sie auf der Detail-Zoom-Stufe verborgen.\n\nBei der Auswahl von „$ALWAYS_SHOW$“ oder „$ALWAYS_HIDE$“ kann die Leistung ein wenig verbessert werden, auf Kosten der fehlenden Grenzen an Küsten."
 SETTINGS_DISCARD_CHANGES: "Änderungen verwerfen"
 SETTING_HUD_SKIN: "Interface-Aussehen"
 hud_skin_auto: "Dynamisch"
 default: "Standard"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nLegt das visuelle Thema des Interface (2-D-Interface) fest, das auf dem Hauptbildschirm des Spiels angezeigt wird.\n\nFalls „$hud_skin_auto$“ ausgewählt wurde, ändert sich das Aussehen des Interface beruhend auf der Kultur, dem Glauben und dem Reichssitz des Spielers."
 SETTING_RICH_PRESENCE: "Angereicherte Anzeige"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nZeigt Euren Freunden Informationen über Eure aktuelle Spielsitzung, sofern Eure Plattform dies unterstützt."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Nach Dynastie benannte Reiche"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nEinige Kulturen benennen ihren Haupttitel nach ihrer Dynastie (wie etwa die Abbasiden)."
 map_table_style_auto: "Dynamisch"
 map_table_style_western: "Standard"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Kartentischstil"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nLegt das Aussehen des Kartentischs fest – die Karte und die 3-D-Umgebung, die beim Herauszoomen angezeigt werden.\n\nIst $map_table_style_auto$ ausgewählt, wird ein Kartentischstil auf Grundlage des aktuellen Spielers und seines Charakters ausgewählt."
 SETTINGS_CATEGORY_STYLING: "Benutzeroberflächenstil"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Krankenheitengrafik"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nLegt fest, ob die Auswirkungen von Krankheiten auf der Karte angezeigt werden sollen"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Legendengrafik"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nLegt fest, ob die Auswirkungen von Legenden auf der Karte angezeigt werden sollen"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Detaillierte [raid|E]-Symbole"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nLegt fest, ob die Kartensymbole für einen [raid|E] in vereinfachter oder detaillierter Form angezeigt werden\n\n#I Bei einer Aktivierung könnt Ihr Alt gedrückt halten, um alle Besitztümer mit Beute anzuzeigen, auf die ein [raid|E] möglich ist.#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Detaillierte [barter|E]-Symbole"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nLegt fest, ob die Kartensymbole für einen [barter|E] in vereinfachter oder detaillierter Form angezeigt werden\n\n#I Bei einer Aktivierung könnt Ihr Alt gedrückt halten, um alle Besitztümer mit Beute anzuzeigen, in denen Ihr [barter|E] betreiben könnt.#!"
 SETTING_PAPER_MAP_STYLE: "Pergamentkartenstil"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nLegt den Anzeigestil fest, wenn die Karte herausgezoomt ist.\n\nWenn „$paper_map_style_auto$“ ausgewählt wird, hält sich der Pergamentkartenstil an den $SETTING_MAP_TABLE_STYLE$."
 paper_map_style_auto: "Dynamisch"
 paper_map_style_western: "Standard"
 paper_map_style_tgp: "Alles unter dem Himmel"
 SETTING_ADAPTIVE_FRAMERATE: "Adaptive Framerate"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Verringert die Bildschirmaktualisierungsrate, wenn das Spielaktualisierungstempo sich verringert, um die Gameplay-Performance zu verbessern."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Wolkenschatten"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nLegt fest, ob der Wolkenschatteneffekt auf dem Gelände angezeigt wird."
 SETTING_HAS_TREE_DITHERING_ENABLED: "Baum-Dithering"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nLegt fest, ob ein Dithering-Effekt bei Bäumen angewendet werden soll, um die Kanten zu glätten."
 SETTING_MAP_BRIGHTNESS: "Pergamentkarten-Helligkeit"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nBestimmt die Helligkeit der Pergamentkarte"
