l_english:
 
 is_your_child_desc: "Is Your Child"
 is_your_close_family_desc: "Is Your Close Family"
 is_your_house_desc: "Is of Your House"
 landed_spouse_desc: "Has a Landed Spouse"
 landed_heir_desc: "Has a Landed Heir"
 has_many_good_relations_desc: "Has Many Friends"
 has_many_bad_relations_desc: "Is Beset by Rivals"
 part_of_feud_desc: "Part of a Feud"
 high_diplomacy_desc: "Has High Diplomacy"
 high_martial_desc: "Has High Martial"
 high_stewardship_desc: "Has High Stewardship"
 high_intrigue_desc: "Has High Intrigue"
 high_learning_desc: "Has High Learning"
 high_prowess_desc: "Has High Prowess"
 high_education_desc: "Is Highly Educated"
 more_beautiful_desc: "Is More Beautiful than Heir"
 more_smart_desc: "Is Smarter than Heir"
 more_fit_desc: "Is Fitter than Heir"
 more_strong_desc: "Is Stronger than Heir"
 more_skillful_desc: "Is More Skillful than Heir"
 has_nickname_desc: "Has a Nickname"
 more_famous_desc: "More Famous than Heir"
 second_in_line_desc: "Second in Line for Inheritance"
 higher_title_desc: "Holds a Higher Title"
 new_liege_desc: "Would be Under a New Liege"
 new_top_liege_desc: "Would be Under a New Top Liege"
 tall_claims_desc: "Holds Important Claims"
 pressed_claims_desc: "Holds Pressed Claims"
 unpressed_claims_desc: "Holds Unpressed Claims"
 inheritance_line_desc: "In Line for Inheritance"
 has_interesting_story_desc: "Has an Interesting Story"
 child_of_destiny_desc: "Is a Child of Destiny"
 virtues_interesting_desc: "Has Virtuous Traits"
 tourney_xp_desc: "Experienced [GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 reveler_xp_desc: "Experienced [GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 mystic_xp_desc: "Experience as a [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 hunter_xp_desc: "Experienced [GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 blademaster_xp_desc: "Experienced [GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 traveler_xp_desc: "Experienced [GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 physician_xp_desc: "Experienced [GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 herbalist_xp_desc: "Experienced [GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 loyal_interesting_desc: "Is [GetTrait('loyal').GetName( GetNullCharacter )]"
 disloyal_interesting_desc: "Is [GetTrait('disloyal').GetName( GetNullCharacter )]"
 faith_warrior_interesting_desc: "Is a [GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc: "Has the [GetTrait('blood_of_prophet').GetName( GetNullCharacter )]"
 varangian_interesting_desc: "Is a [GetTrait('varangian').GetName( GetNullCharacter )]"
 poet_interesting_desc: "Is a [GetTrait('lifestyle_poet').GetName( GetNullCharacter )]"
 peasant_leader_interesting_desc: "Is a [GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 populist_leader_interesting_desc: "Is a [GetTrait('populist_leader').GetName( GetNullCharacter )]"
 berserker_interesting_desc: "Is a [GetTrait('berserker').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc: "Is [GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 scaly_interesting_desc: "Has [GetTrait('scaly').GetName( GetNullCharacter )] Skin"
 albino_interesting_desc: "Is an [GetTrait('albino').GetName( GetNullCharacter )]"
 dwarf_interesting_desc: "Is a [GetTrait('dwarf').GetName( GetNullCharacter )]"
 giant_interesting_desc: "Is a [GetTrait('giant').GetName( GetNullCharacter )]"
 devoted_interesting_desc: "Is a [GetTrait('devoted').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc: "Is [GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "Is a [GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "Is [GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc: "Is [GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc: "Is a Diarch"
 ruler_in_foreign_lands_interesting_desc: "Is a Ruler in Foreign Lands"
 valiant_knight_interesting_desc: "Is a Valiant Knight"
 sinful_bastard_interesting_desc: "Is a Sinful [GetTrait('bastard').GetName( GetNullCharacter )]"
 adventurer_interesting_desc: "Is an Adventurer"
 liege_crusader_king_liege_lineage_interesting_desc: "Liege of [GetTrait('crusader_king').GetName( GetNullCharacter )] Lineage"
 holy_site_steward_interesting_desc: "Capital is a Holy Site"
 has_a_legend_interesting_desc: "Has a Legend"
 weak_hook_liege_interesting_desc: "Has Weak Hook on Liege"
 strong_hook_liege_interesting_desc: "Has Strong Hook on Liege"
 beloved_by_pope_interesting_desc: "Beloved by the Pope"
 head_of_faith_interesting_desc: "Is a Head of Faith"
 stronger_than_liege_interesting_desc: "Stronger than Liege"
 small_king_interesting_desc: "Is a Small Kingdom Ruler"
 can_feudalize_interesting_desc: "Can Feudalize"
 multiduke_interesting_desc: "Holds many Duchies"
 legitimacy_interesting_desc: "Extremely Legitimate Ruler"
 non_dominant_gender_ambitious_char_interesting_desc: "Is an Ambitious Non-Dominant Gender Character"
 non_dominant_gender_ruler_interesting_desc: "Is a Non-Dominant Gender Ruler"
 treacherous_schemer_interesting_desc: "Is a Treacherous Schemer"
 kind_hearted_diplomat_interesting_desc: "Is a Kind-Hearted Diplomat"
 different_faith_interesting_desc: "Of Different Faith"
 greedy_steward_interesting_desc: "Is a Greedy Steward"
 brazen_commander_interesting_desc: "Is a Brazen Commander"
 pious_theologian_interesting_desc: "Is a Pious Theologian"
 salacious_seducer_interesting_desc: "Is a Salacious Seducer"
 high_skills_desc: "Skills are Very High"
 killed_a_lot_interesting_desc: "Killed Over 10 People"
 has_both_good_and_bad_genetics_desc: "Has Both Good and Bad Genetic Traits"
 good_genetics_desc: "Good Genetic Traits"
 bad_genetics_desc: "Bad Genetic Traits"
 holds_rome_interesting_desc: "Holds the [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Holds the [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Holds the [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Holds the [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Holds the [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Controls Special Buildings"
 has_historical_artifacts_interesting_desc: "Owns Unique Historical Artifacts"
 underrepresented_faith_interesting_desc: "Is of an Underrepresented Faith"
 underrepresented_culture_interesting_desc: "Is of an Underrepresented Culture"
 outside_realm_desc: "Independent Ruler"
 knows_many_secrets_interesting_desc: "Knows Many Secrets"
 has_secrets_interesting_desc: "Has Secrets"
 extremely_wealthy_interesting_desc: "Very Wealthy"
 landless_heir_uninteresting_desc: "Unlanded Title Heir"
 three_virtues_desc: "Has Three Virtues"
 three_sins_desc: "Has Three Sins"

 skills_difficulty: "From Skills"
 legitimacy_difficulty: "From Legitimacy"
 virtuous_traits_difficulty: "Has Virtuous Traits"
 physique_good_3_difficulty: "Is [GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 physique_good_2_difficulty: "Is [GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_1_difficulty: "Is [GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty: "Is [GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty: "Is [GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty: "Is [GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty: "Is [GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty: "Is [GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty: "Is [GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 shrewd_difficulty: "Is [GetTrait('shrewd').GetName( GetNullCharacter )]"
 strong_difficulty: "Is [GetTrait('strong').GetName( GetNullCharacter )]"
 sinful_traits_difficulty: "Has Sinful Traits"
 incapable_difficulty: "Is [GetTrait('incapable').GetName( GetNullCharacter )]"
 leper_difficulty: "Is a [GetTrait('leper').GetName( GetNullCharacter )]"
 maimed_difficulty: "Is [GetTrait('maimed').GetName( GetNullCharacter )]"
 inbred_difficulty: "Is [GetTrait('inbred').GetName( GetNullCharacter )]"
 severely_wounded_difficulty: "Is Severely Wounded"
 disinherited_difficulty: "Is [GetTrait('disinherited').GetName( GetNullCharacter )]"
 sickly_difficulty: "Is [GetTrait('sickly').GetName( GetNullCharacter )]"
 poxed_difficulty: "Has the [GetTrait('great_pox').GetName( GetNullCharacter )]"
 blind_difficulty: "Is [GetTrait('blind').GetName( GetNullCharacter )]"
 infirm_difficulty: "Is [GetTrait('infirm').GetName( GetNullCharacter )]"
 eunuch_difficulty: "Is a [GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 lunatic_difficulty: "Is a [GetTrait('lunatic').GetName( GetNullCharacter )]"
 murderer_difficulty: "Is a [GetTrait('murderer').GetName( GetNullCharacter )]"
 excommunicated_difficulty: "Is Excommunicated"
 bleeder_difficulty: "Is a [GetTrait('bleeder').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty: "Is [GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty: "Is [GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty: "Is [GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty: "Is [GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty: "Is [GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_1_difficulty: "Is [GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty: "Is [GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty: "Is [GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty: "Is [GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 dull_difficulty: "Is [GetTrait('dull').GetName( GetNullCharacter )]"
 weak_difficulty: "Is [GetTrait('weak').GetName( GetNullCharacter )]"
 sodomite_difficulty: "Is a [GetTrait('sodomite').GetName( GetNullCharacter )]"
 incestuous_difficulty: "Is [GetTrait('incestuous').GetName( GetNullCharacter )]"
 fornicator_difficulty: "Is a [GetTrait('fornicator').GetName( GetNullCharacter )]"
 adulterer_difficulty: "Is an [GetTrait('adulterer').GetName( GetNullCharacter )]"
 cannibal_difficulty: "Is a [GetTrait('cannibal').GetName( GetNullCharacter )]"
 witch_difficulty: "Is a [GetTrait('witch').GetName( GetNullCharacter )]"
 kinslayer_difficulty: "Is a [GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 flagellant_difficulty: "Is a [GetTrait('flagellant').GetName( GetNullCharacter )]"
 improvident_difficulty: "Is [GetTrait('improvident').GetName( GetNullCharacter )]"
 profligate_difficulty: "Is [GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty: "Is [GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty: "Is a [GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty: "Is [GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty: "Is [GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty: "Is [GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty: "Is [GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty: "Is [GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty: "Has [GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty: "Is [GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "Is [GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty: "Is [GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty: "Is [GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "Is [GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty: "Is a [GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty: "Has Weak Heritage"
 comfort_eater_difficulty: "Is a [GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "Is [GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty: "Is [GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty: "Is [GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty: "Is [GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty: "Is a [GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty: "Is [GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty: "Has [GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 wounded_difficulty: "Is [GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty: "Is an [GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty: "Has a [GetTrait('lisping').GetName( GetNullCharacter )] Impediment"
 stuttering_difficulty: "Has a [GetTrait('stuttering').GetName( GetNullCharacter )] Impediment"
 giant_difficulty: "Is a [GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty: "Has [GetTrait('scaly').GetName( GetNullCharacter )] Skin"
 clubfooted_difficulty: "Is [GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty: "Is a [GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty: "Is [GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty: "Is [GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "Is [GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty: "Is a [GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty: "At War"
 losing_war_difficulty: "Losing Wars"
 faction_difficulty: "Targeted by Powerful Factions"
 powerful_neighbors_difficulty: "Powerful Neighboring Rulers"
 military_difficulty: "Military Strength"
 rivals_difficulty: "Has Rivals"
 primary_heir_wrong_dynasty_difficulty: "Primary Heir from Wrong Dynasty"
 children_wrong_dynasty_difficulty: "Children are of the Wrong Dynasty"
 hostile_faith_liege_difficulty: "Liege of Hostile Faith"
 nonpreferred_gender_difficulty: "Non-Preferred Gender in Faith"
 wrong_lineality_difficulty: "Wrong Lineality in Marriage"
 stress_level_difficulty: "High Stress Level"
 gold_difficulty: "Excessive Wealth"
 debt_level_difficulty: "High Debt Level"
 is_ill_difficulty: "Suffering from Debilitating Illness"
 imprisoned_difficulty: "Imprisoned"
 elder_difficulty: "Advanced Age"
 poor_health_difficulty: "Poor Health"
 is_a_vassal_difficulty: "Is a Vassal"
 non_adult_difficulty: "Child"
 weak_domain_difficulty: "Weak Domain"
 unlanded_difficulty: "Holds no Titles"
 
 character_difficulty_text: "Difficulty: [Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "Difficulty Breakdown"
 choose_destiny_header_text: "Choose a New Destiny"
 will_become_adventurer: "Will become an [GetGovernment('landless_adventurer_government').GetName]"
 character_interest_breakdown_header: "Interesting Aspects"

 different_government_desc: "Has a Different Government"
 opposite_struggle_faction_desc: "Opposite Faction in a Struggle"
