l_spanish:
 is_your_child_desc: "Es tu vástago"
 is_your_close_family_desc: "Es familia cercana tuya"
 is_your_house_desc: "Es de tu casa"
 landed_spouse_desc: "Tiene un cónyuge con tierras"
 landed_heir_desc: "Tiene un heredero con tierras"
 has_many_good_relations_desc: "Tiene muchos amigos"
 has_many_bad_relations_desc: "Le acosan los rivales"
 part_of_feud_desc: "Parte de una enemistad"
 high_diplomacy_desc: "Tiene gran diplomacia"
 high_martial_desc: "Tiene gran marcialidad"
 high_stewardship_desc: "Tiene gran administración"
 high_intrigue_desc: "Tiene gran intriga"
 high_learning_desc: "Tiene gran aprendizaje"
 high_prowess_desc: "Tiene gran destreza"
 high_education_desc: "Tiene una gran educación"
 more_beautiful_desc: "Es de mayor belleza que el heredero"
 more_smart_desc: "Es más inteligente que el heredero"
 more_fit_desc: "Está más en forma que el heredero"
 more_strong_desc: "Es más fuerte que el heredero"
 more_skillful_desc: "Es más hábil que el heredero"
 has_nickname_desc: "Tiene un apodo"
 more_famous_desc: "Más famoso que el heredero"
 second_in_line_desc: "Segundo lugar en la sucesión"
 higher_title_desc: "Tiene un título superior"
 new_liege_desc: "Estaría bajo un nuevo señor"
 new_top_liege_desc: "Estaría bajo un nuevo señor principal"
 tall_claims_desc: "Posee derechos importantes"
 pressed_claims_desc: "Posee derechos reivindicados"
 unpressed_claims_desc: "Posee derechos no reivindicados"
 inheritance_line_desc: "En la línea de sucesión"
 has_interesting_story_desc: "Tiene una historia interesante"
 child_of_destiny_desc: "Es un hijo del destino"
 virtues_interesting_desc: "Tiene rasgos virtuosos"
 tourney_xp_desc: "[GetTrait('tourney_participant').GetName( GetNullCharacter )] con experiencia"
 reveler_xp_desc: "[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )] con experiencia"
 mystic_xp_desc: "Experiencia como [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )|l]"
 hunter_xp_desc: "[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )] con experiencia"
 blademaster_xp_desc: "[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )] con experiencia"
 traveler_xp_desc: "[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )] con experiencia"
 physician_xp_desc: "[GetTrait('lifestyle_physician').GetName( GetNullCharacter )] con experiencia"
 herbalist_xp_desc: "[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )] con experiencia"
 loyal_interesting_desc: "Es [GetTrait('loyal').GetName( GetNullCharacter )|l]"
 disloyal_interesting_desc: "Es [GetTrait('disloyal').GetName( GetNullCharacter )|l]"
 faith_warrior_interesting_desc: "Es un [GetTrait('faith_warrior').GetName( GetNullCharacter )|l]"
 blood_of_prophet_interesting_desc: "Lleva la [GetTrait('blood_of_prophet').GetName( GetNullCharacter )|l]"
 varangian_interesting_desc: "Es un [GetTrait('varangian').GetName( GetNullCharacter )|l]"
 poet_interesting_desc: "Es de carácter [GetTrait('lifestyle_poet').GetName( GetNullCharacter )|l]"
 peasant_leader_interesting_desc: "Es un [GetTrait('peasant_leader').GetName( GetNullCharacter )|l]"
 populist_leader_interesting_desc: "Es un [GetTrait('populist_leader').GetName( GetNullCharacter )|l]"
 berserker_interesting_desc: "Es un [GetTrait('berserker').GetName( GetNullCharacter )|l]"
 born_in_the_purple_interesting_desc: "Es [GetTrait('born_in_the_purple').GetName( GetNullCharacter )|l]"
 scaly_interesting_desc: "Es [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 albino_interesting_desc: "Es [GetTrait('albino').GetName( GetNullCharacter )|l]"
 dwarf_interesting_desc: "Es un [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 giant_interesting_desc: "Es un [GetTrait('giant').GetName( GetNullCharacter )|l]"
 devoted_interesting_desc: "Es [GetTrait('devoted').GetName( GetNullCharacter )|l]"
 pure_blooded_interesting_desc: "Es [GetTrait('pure_blooded').GetName( GetNullCharacter )|l]"
 crusader_king_interesting_desc: "Es un [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 disinherited_interesting_desc: "Está [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 blind_interesting_desc: "Está [GetTrait('blind').GetName( GetNullCharacter )|l]"
 is_diarch_interesting_desc: "Es diarca"
 ruler_in_foreign_lands_interesting_desc: "Es gobernante en tierras extranjeras"
 valiant_knight_interesting_desc: "Es un caballero valiente"
 sinful_bastard_interesting_desc: "Es un [GetTrait('bastard').GetName( GetNullCharacter )|l] pecador"
 adventurer_interesting_desc: "Es un aventurero"
 liege_crusader_king_liege_lineage_interesting_desc: "Señor del linaje de [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 holy_site_steward_interesting_desc: "La capital es un lugar sagrado"
 has_a_legend_interesting_desc: "Tiene una leyenda"
 weak_hook_liege_interesting_desc: "Tiene un anzuelo débil sobre el señor"
 strong_hook_liege_interesting_desc: "Tiene un anzuelo fuerte sobre el señor"
 beloved_by_pope_interesting_desc: "Tiene el aprecio del papa"
 head_of_faith_interesting_desc: "Es un cabeza de la fe"
 stronger_than_liege_interesting_desc: "Más fuerte que el señor"
 small_king_interesting_desc: "Es el gobernante de un pequeño reino"
 can_feudalize_interesting_desc: "Se puede feudalizar"
 multiduke_interesting_desc: "Posee muchos ducados"
 legitimacy_interesting_desc: "Gobernante sumamente legítimo"
 non_dominant_gender_ambitious_char_interesting_desc: "Es un personaje ambicioso de género no dominante"
 non_dominant_gender_ruler_interesting_desc: "Es un gobernante de género no dominante"
 treacherous_schemer_interesting_desc: "Es un intrigante traicionero"
 kind_hearted_diplomat_interesting_desc: "Es un diplomático bondadoso"
 different_faith_interesting_desc: "De fe diferente"
 greedy_steward_interesting_desc: "Es un administrador codicioso"
 brazen_commander_interesting_desc: "Es un comandante osado"
 pious_theologian_interesting_desc: "Es un teólogo piadoso"
 salacious_seducer_interesting_desc: "Es un seductor salaz"
 high_skills_desc: "Tiene habilidades muy fuertes"
 killed_a_lot_interesting_desc: "Ha matado a más de 10 personas"
 has_both_good_and_bad_genetics_desc: "Tiene rasgos genéticos buenos y malos"
 good_genetics_desc: "Rasgos genéticos buenos"
 bad_genetics_desc: "Rasgos genéticos malos"
 holds_rome_interesting_desc: "Posee [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Posee [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Posee [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Posee [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Posee [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Controla edificios especiales"
 has_historical_artifacts_interesting_desc: "Posee artefactos históricos únicos"
 underrepresented_faith_interesting_desc: "Es de una fe con poca representación"
 underrepresented_culture_interesting_desc: "Es de una cultura con poca representación"
 outside_realm_desc: "Gobernante independiente"
 knows_many_secrets_interesting_desc: "Sabe muchos secretos"
 has_secrets_interesting_desc: "Tiene secretos"
 extremely_wealthy_interesting_desc: "Con muchas riquezas"
 landless_heir_uninteresting_desc: "Heredero de título sin tierras"
 three_virtues_desc: "Tiene tres virtudes"
 three_sins_desc: "Tiene tres pecados"
 skills_difficulty: "Por habilidades"
 legitimacy_difficulty: "Por legitimidad"
 virtuous_traits_difficulty: "Tiene rasgos virtuosos"
 physique_good_3_difficulty: "Es [GetTrait('physique_good_3').GetName( GetNullCharacter )|l]"
 physique_good_2_difficulty: "Es [GetTrait('physique_good_2').GetName( GetNullCharacter )|l]"
 physique_good_1_difficulty: "Está [GetTrait('physique_good_1').GetName( GetNullCharacter )|l]"
 intellect_good_3_difficulty: "Es [GetTrait('intellect_good_3').GetName( GetNullCharacter )|l]"
 intellect_good_2_difficulty: "Es [GetTrait('intellect_good_2').GetName( GetNullCharacter )|l]"
 intellect_good_1_difficulty: "Es [GetTrait('intellect_good_1').GetName( GetNullCharacter )|l]"
 beauty_good_3_difficulty: "Es [GetTrait('beauty_good_3').GetName( GetNullCharacter )|l]"
 beauty_good_2_difficulty: "Es [GetTrait('beauty_good_2').GetName( GetNullCharacter )|l]"
 beauty_good_1_difficulty: "Es [GetTrait('beauty_good_1').GetName( GetNullCharacter )|l]"
 shrewd_difficulty: "Es [GetTrait('shrewd').GetName( GetNullCharacter )|l]"
 strong_difficulty: "Es [GetTrait('strong').GetName( GetNullCharacter )|l]"
 sinful_traits_difficulty: "Tiene rasgos pecaminosos"
 incapable_difficulty: "Es [GetTrait('incapable').GetName( GetNullCharacter )|l]"
 leper_difficulty: "Es [GetTrait('leper').GetName( GetNullCharacter )|l]"
 maimed_difficulty: "Está [GetTrait('maimed').GetName( GetNullCharacter )|l]"
 inbred_difficulty: "Es [GetTrait('inbred').GetName( GetNullCharacter )|l]"
 severely_wounded_difficulty: "Sufre graves heridas"
 disinherited_difficulty: "Está [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 sickly_difficulty: "Es [GetTrait('sickly').GetName( GetNullCharacter )|l]"
 poxed_difficulty: "Tiene [GetTrait('great_pox').GetName( GetNullCharacter )|l]"
 blind_difficulty: "Está [GetTrait('blind').GetName( GetNullCharacter )|l]"
 infirm_difficulty: "Es [GetTrait('infirm').GetName( GetNullCharacter )|l]"
 eunuch_difficulty: "Es un [GetTrait('eunuch_1').GetName( GetNullCharacter )|l]"
 lunatic_difficulty: "Es un [GetTrait('lunatic').GetName( GetNullCharacter )|l]"
 murderer_difficulty: "Es un [GetTrait('murderer').GetName( GetNullCharacter )|l]"
 excommunicated_difficulty: "Ha recibido excomunión"
 bleeder_difficulty: "Es un [GetTrait('bleeder').GetName( GetNullCharacter )|l]"
 physique_bad_3_difficulty: "Es [GetTrait('physique_bad_3').GetName( GetNullCharacter )|l]"
 physique_bad_2_difficulty: "Es [GetTrait('physique_bad_2').GetName( GetNullCharacter )|l]"
 physique_bad_1_difficulty: "Es [GetTrait('physique_bad_1').GetName( GetNullCharacter )|l]"
 intellect_bad_3_difficulty: "Es [GetTrait('intellect_bad_3').GetName( GetNullCharacter )|l]"
 intellect_bad_2_difficulty: "Es [GetTrait('intellect_bad_2').GetName( GetNullCharacter )|l]"
 intellect_bad_1_difficulty: "Es [GetTrait('intellect_bad_1').GetName( GetNullCharacter )|l]"
 beauty_bad_3_difficulty: "Es [GetTrait('beauty_bad_3').GetName( GetNullCharacter )|l]"
 beauty_bad_2_difficulty: "Es [GetTrait('beauty_bad_2').GetName( GetNullCharacter )|l]"
 beauty_bad_1_difficulty: "Es [GetTrait('beauty_bad_1').GetName( GetNullCharacter )|l]"
 dull_difficulty: "Es [GetTrait('dull').GetName( GetNullCharacter )|l]"
 weak_difficulty: "Es [GetTrait('weak').GetName( GetNullCharacter )|l]"
 sodomite_difficulty: "Es un [GetTrait('sodomite').GetName( GetNullCharacter )|l]"
 incestuous_difficulty: "Es [GetTrait('incestuous').GetName( GetNullCharacter )|l]"
 fornicator_difficulty: "Es un [GetTrait('fornicator').GetName( GetNullCharacter )|l]"
 adulterer_difficulty: "Es [GetTrait('adulterer').GetName( GetNullCharacter )|l]"
 cannibal_difficulty: "Es un [GetTrait('cannibal').GetName( GetNullCharacter )|l]"
 witch_difficulty: "Es [GetTrait('witch').GetName( GetNullCharacter )|l]"
 kinslayer_difficulty: "Es un [GetTrait('kinslayer_1').GetName( GetNullCharacter )|l]"
 flagellant_difficulty: "Es un [GetTrait('flagellant').GetName( GetNullCharacter )|l]"
 improvident_difficulty: "Es [GetTrait('improvident').GetName( GetNullCharacter )|l]"
 profligate_difficulty: "Es [GetTrait('profligate').GetName( GetNullCharacter )|l]"
 disfigured_difficulty: "Está [GetTrait('disfigured').GetName( GetNullCharacter )|l]"
 drunkard_difficulty: "Es un [GetTrait('drunkard').GetName( GetNullCharacter )|l]"
 possessed_difficulty: "Está [GetTrait('possessed').GetName( GetNullCharacter )|l]"
 depressed_difficulty: "Está [GetTrait('depressed').GetName( GetNullCharacter )|l]"
 infertile_difficulty: "Es [GetTrait('infertile').GetName( GetNullCharacter )|l]"
 spindly_difficulty: "Es [GetTrait('spindly').GetName( GetNullCharacter )|l]"
 paranoid_difficulty: "Es [GetTrait('paranoid').GetName( GetNullCharacter )|l]"
 gout_difficulty: "Está [GetTrait('gout_ridden').GetName( GetNullCharacter )|l]"
 wheezing_difficulty: "Está [GetTrait('wheezing').GetName( GetNullCharacter )|l]"
 craven_difficulty: "Es [GetTrait('craven').GetName( GetNullCharacter )|l]"
 shy_difficulty: "Es [GetTrait('shy').GetName( GetNullCharacter )|l]"
 decadent_difficulty: "Es [GetTrait('decadent').GetName( GetNullCharacter )|l]"
 denounced_difficulty: "Es [GetTrait('denounced').GetName( GetNullCharacter )|l]"
 bastard_difficulty: "Es un [GetTrait('bastard').GetName( GetNullCharacter )|l]"
 weak_heritage_difficulty: "Tiene una herencia débil"
 comfort_eater_difficulty: "Es un [GetTrait('comfort_eater').GetName( GetNullCharacter )|l]"
 inappetetic_difficulty: "Es [GetTrait('inappetetic').GetName( GetNullCharacter )|l]"
 reclusive_difficulty: "Está [GetTrait('reclusive').GetName( GetNullCharacter )|l]"
 irritable_difficulty: "Es [GetTrait('irritable').GetName( GetNullCharacter )|l]"
 rakish_difficulty: "Es [GetTrait('rakish').GetName( GetNullCharacter )|l]"
 hashishiyah_difficulty: "Es un [GetTrait('hashishiyah').GetName( GetNullCharacter )|l]"
 celibate_difficulty: "Es [GetTrait('celibate').GetName( GetNullCharacter )|l]"
 lovers_pox_difficulty: "Tiene [GetTrait('lovers_pox').GetName( GetNullCharacter )|l]"
 wounded_difficulty: "Está [GetTrait('wounded_1').GetName( GetNullCharacter )|l]"
 albino_difficulty: "Es [GetTrait('albino').GetName( GetNullCharacter )|l]"
 lisping_difficulty: "Tiene un defecto del habla [GetTrait('lisping').GetName( GetNullCharacter )|l]"
 stuttering_difficulty: "Es [GetTrait('stuttering').GetName( GetNullCharacter )|l]"
 giant_difficulty: "Es un [GetTrait('giant').GetName( GetNullCharacter )|l]"
 scaly_difficulty: "Es [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 clubfooted_difficulty: "Tiene el [GetTrait('clubfooted').GetName( GetNullCharacter )|l]"
 dwarf_difficulty: "Es un [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 hunchbacked_difficulty: "Está [GetTrait('hunchbacked').GetName( GetNullCharacter )|l]"
 lazy_difficulty: "Es [GetTrait('lazy').GetName( GetNullCharacter )|l]"
 gluttonous_difficulty: "Es [GetTrait('gluttonous').GetName( GetNullCharacter )|l]"
 deviant_difficulty: "Es un [GetTrait('deviant').GetName( GetNullCharacter )|l]"
 at_war_difficulty: "En guerra"
 losing_war_difficulty: "Pierde guerras"
 faction_difficulty: "Objetivo de facciones poderosas"
 powerful_neighbors_difficulty: "Gobernantes vecinos poderosos"
 military_difficulty: "Fuerza militar"
 rivals_difficulty: "Tiene rivales"
 primary_heir_wrong_dynasty_difficulty: "Heredero principal de la dinastía errónea"
 children_wrong_dynasty_difficulty: "Vástagos de la dinastía errónea"
 hostile_faith_liege_difficulty: "Señor de fe hostil"
 nonpreferred_gender_difficulty: "Género no preferido de la fe"
 wrong_lineality_difficulty: "Linaje erróneo en el matrimonio"
 stress_level_difficulty: "Nivel de estrés alto"
 gold_difficulty: "Riquezas excesivas"
 debt_level_difficulty: "Nivel de endeudamiento alto"
 is_ill_difficulty: "Sufre una enfermedad debilitante"
 imprisoned_difficulty: "En prisión"
 elder_difficulty: "Edad avanzada"
 poor_health_difficulty: "Mala salud"
 is_a_vassal_difficulty: "Es un vasallo"
 non_adult_difficulty: "Criatura"
 weak_domain_difficulty: "Dominio débil"
 unlanded_difficulty: "No posee títulos"
 character_difficulty_text: "Dificultad: [Character.Custom('CharacterDifficulty')|l]"
 character_difficulty_breakdown_header: "Análisis de dificultad"
 choose_destiny_header_text: "Elegir un nuevo destino"
 will_become_adventurer: "Se convertirá en [GetGovernment('landless_adventurer_government').GetName|l]"
 character_interest_breakdown_header: "Aspectos interesantes"
 different_government_desc: "Tiene un gobierno distinto"
 opposite_struggle_faction_desc: "Facción opuesta en una contienda"
