l_spanish:
 SETTING_DEBUG_SAVES: "Depuraciones guardadas"
 SETTING_TUTORIAL: "Tutorial"
 SETTING_DISABLED_HINTS: "Pistas desactivadas"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Retardo herramientas"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nEstablece el tiempo que tardan en aparecer las ayudas emergentes."
 SETTING_TOOLTIP_UNLOCK_TIME: "Retardo de desbloqueo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nEstablece el tiempo que tardan en desbloquearse las ayudas emergentes."
 SETTING_TOOLTIP_LOCK_TIME: "Retardo bloqueo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Retardo bloqueo abierto"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes cuando ya se está mostrando otra ayuda."
 #Audio
 SETTING_Sound_Effects: "Todos los efectos de sonido"
 SETTING_Sound_Effects_TOOLTIP: "#T Volumen de efectos\n#!Establece el volumen de TODOS los efectos de sonido."
 SETTING_Ambience: "Ambiente"
 SETTING_Ambience_TOOLTIP: "#T Volumen de ambiente\n#!Establece el volumen de los sonidos ambientales."
 SETTING_TOOLTIP_MODE: "Modo ayuda emergente"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nEstablece la forma en que se «fija» la ayuda emergente, de modo que se puedan consultar ayudas dentro de otras ayudas."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendencia del ratón"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nLa ayuda emergente se quedará fija hasta que apartes el cursor."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Bloqueo de acción"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPulsa el #V botón central del ratón#! para bloquear y desbloquear la ayuda emergente."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Pausa temporal"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nLa ayuda emergente se queda fija si no mueves el cursor durante un rato. #weak (Opción predeterminada.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Varios"
 SETTINGS_CATEGORY_TOOLTIPS: "Ayuda emergente"
 SETTINGS_CATEGORY_SFX: "Efectos de sonido específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "General"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Controles de juego"
 SETTINGS_CATEGORY_SAVE_GAMES: "Partidas guardadas"
 SETTINGS_CATEGORY_LANGUAGE: "Idioma"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avanzados - General"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Avanzados - Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Avanzados - Jugadores"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Retratos"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Experiencia"
 SETTINGS_CATEGORY_MULTIPLAYER: "Multijugador"
 SETTINGS_CATEGORY_MAP: "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Mostrar gráficamente las enfermedades y heridas"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nEstablece si mostrar enfermedades y heridas gráficamente en los retratos de personajes."
 SETTING_SHOW_NUDITY: "Mostrar desnudos"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDetermina si los personajes pueden aparecer desnudos."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Contenido descargable"
 SETTING_SHOW_CONTENT_SOURCE: "Mostrar DLC de evento"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nMarca si los eventos muestran de qué DLC proceden."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Corte real, recorrido en inactividad"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nIndica si la cámara en la corte real debe recorrer suavemente la corte mientras esté inactiva.\n\nEste ajuste no tiene efecto si la opción Personajes animados está apagado."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Corte real, transiciones suaves"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nIndica si la cámara en la corte real debe desplazarse suavemente a una nueva posición.\n\nEste ajuste no tiene efecto si Personajes animados está apagado."
 NEVER: "Nunca"
 MONTHLY: "Todos los meses"
 HALFYEAR: "Cada 6 meses"
 YEARLY: "Todos los años"
 FIVE_YEAR: "Cada 5 años"
 SETTINGS_CATEGORY_TUTORIAL: "Tutorial"
 SETTING_REACTIVE_TUTORIAL: "Mostrar consejos reactivos"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nEstablece si el juego debe mostrar consejos de tutorial según se juega. Es útil para los nuevos jugadores de Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Mostrar sugerencias"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nEstablece si el juego te sugiere actividades a intervalos regulares. Útil para aquellos jugadores que estén descubriendo Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Reiniciar consejos reactivos"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Reiniciar consejos reactivos#!\nSe volverán a mostrar los consejos reactivos que hayas visto antes."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Reiniciar consejos reactivos"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "¿De verdad quieres reiniciar los consejos reactivos?"
 SETTING_ADVANCED_SHADERS: "Efectos de sombreado avanzados"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Efectos de sombreado avanzados\n#!Esta opción activará los efectos de sombreado avanzados.\n\nSi los desactivas, puede mejorar el rendimiento, pero ciertos efectos se verán peor, como el terreno o el agua."
 SETTING_WINTER_PARTICLE_EFFECTS: "Efectos partículas invernales"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermina si se mostrarán efectos de partículas cuando el invierno esté activo en algunas partes del mapa.\n\nSi se desactiva puede mejorar el rendimiento."
 SETTING_RESET_CAMERA_ROTATION: "Restablecer rotación de la cámara"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina si la cámara debe restablecer automáticamente la posición por defecto una vez girada."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Inclinar la cámara al alejarse"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nControla si la cámara debe tender hacia la inclinación por defecto al alejar la imagen."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Personajes de fondo en la escena de corte"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina si en la escena 3D de la corte real debe mostrar personajes de fondo menos importantes."
 SETTING_MAP_HIGHLIGHT: "Resalte del cursor en el mapa"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina la intensidad de los resaltes del cursor en el mapa"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Resaltado del señor supremo en el mapa"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nDetermina cuándo se resalta el señor supremo de un señorío al seleccionar el señorío."
 OPTION_ALWAYS: "Siempre"
 OPTION_TRIBUTARY_ONLY: "Solo tributarios"
 BASED_ON_ZOOM_LEVEL: "Dinámico"
 ALWAYS_HIDE: "Ocultar siempre"
 ALWAYS_SHOW: "Mostrar siempre"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Fronteras costeras"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nCon esta opción se determina si se mostrarán o no las fronteras costeras.\nSi eliges $BASED_ON_ZOOM_LEVEL$, se ocultarán cuando acerques la imagen en detalle.\n\nSi eliges $ALWAYS_SHOW$ o $ALWAYS_HIDE$, puede mejorar el rendimiento pero las fronteras costeras del señorío no se mostrarán y ocultarán automáticamente."
 SETTINGS_DISCARD_CHANGES: "Descartar cambios"
 SETTING_HUD_SKIN: "Interfaz HUD"
 hud_skin_auto: "Dinámica"
 default: "Predeterminada"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nControla el tema visual de la interfaz HUD – IU 2D de la pantalla principal del juego.\n\nSi se ha seleccionado $hud_skin_auto$, el HUD cambiará dependiendo de la cultura, fe y capital del señorío del jugador."
 SETTING_RICH_PRESENCE: "Presencia avanzada"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nMuestra información sobre tu sesión de juego actual a tus amigos, si tu plataforma lo permite."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Señoríos nombrados a partir de dinastías"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nAlgunas culturas denominan a su título principal a partir de su dinastía (p.ej.: abasidas)."
 map_table_style_auto: "Dinámico"
 map_table_style_western: "Predeterminado"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Estilo de mesa del mapa"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nControla el estilo visual de la mesa del mapa – el mapa y el entorno 3D al alejar la imagen.\n\nSi se ha seleccionado $map_table_style_auto$, se elegirá un estilo de mesa del mapa basado en el jugador actual y su personaje."
 SETTINGS_CATEGORY_STYLING: "Estilo de interfaz"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Gráficos de enfermedad"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nControla si los efectos de las enfermedades aparecen en el mapa"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Gráficos de leyenda"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nControla si los efectos de las leyendas aparecen en el mapa"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Iconos de [raid|El] detallados"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nMarca si los iconos de mapa de [raid|lE] muestran las versiones simplificadas o detalladas\n\n#I Si está activado, mantener Alt para mostrar todas las posesiones con botín que se pueden [Concept('raid', 'asaltar')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Iconos de [Concept('barter', 'trueque')|E] detallados"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nMarca si los iconos de mapa de [Concept('barter', 'trueque')|E] muestran las versiones simplificadas o detalladas\n\n#I Si está activado, mantener Alt para mostrar todas las posesiones con botín que se pueden [Concept('barter', 'trocar')|E].#!"
 SETTING_PAPER_MAP_STYLE: "Estilo del mapa de papel"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nDecide el estilo del mapa al alejar la imagen.\n\nSi se elige $paper_map_style_auto$, el mapa de papel seguirá el estilo empleado por «$SETTING_MAP_TABLE_STYLE$»."
 paper_map_style_auto: "Dinámico"
 paper_map_style_western: "Predeterminado"
 paper_map_style_tgp: "All Under Heaven"
 SETTING_ADAPTIVE_FRAMERATE: "Velocidad de fotogramas adaptativa"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Reduce la tasa de actualización de la pantalla si la velocidad de actualización del juego disminuye para mejorar el rendimiento."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Sombras de nubes"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nControla si los efectos de las sombras de las nubes se muestran sobre el terreno."
 SETTING_HAS_TREE_DITHERING_ENABLED: "Tramado de árboles"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nControla si los efectos de tramado se aplican a los árboles para suavizar los bordes."
 SETTING_MAP_BRIGHTNESS: "Brillo del mapa de papel"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina la intensidad del brillo del mapa de papel"
