l_japanese:
 message_settings_tab_settings: "設定"
 message_settings_tab_log: "メッセージログ"
 MESSAGE_SETTINGS_WINDOW_NAME: "メッセージ設定"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I クリックでメッセージ設定を開きます#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nフィルターグループごとにメッセージの頻度と表示を調節します。"
 MESSAGE_SETTINGS_WINDOW_RESET: "デフォルトにリセット"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T メッセージ設定をリセット#!\n#I クリックで現在の変更内容をデフォルト設定にリセットします#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "変更内容を適用"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I クリックでメッセージ設定を閉じ、現在の変更内容を保存します#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! フィード"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! トースト"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! ポップアップ"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! なし"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak （$SIZE$）#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "フィルターグループ"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "メッセージのフィルターグループの名前"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "表示方法"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "このフィルターグループのメッセージの表示方法"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "一時停止"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "このフィルターのメッセージが表示された時にゲームを一時停止するかどうかを設定します"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T 自動停止を切り替え#!\n#I このフィルターのメッセージが表示されるとゲームが一時停止するように切り替えます#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T メッセージを閉じる#!\n#I クリックで現在のメッセージを閉じ、キュー内の次のメッセージを表示#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "カスタムメッセージ"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T カスタムメッセージ#!\n#I クリックで自分宛てにカスタムメッセージを作成し、受け取り日を選択します#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "メッセージの受け取り日：[DATE.GetString|V]"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "タイトル："
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "詳細："
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "破棄"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T メッセージを破棄#!\n#I クリックで現在のメッセージを破棄します#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "送信"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T 送信#!\n#I クリックで現在のメッセージを送信します#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "日"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "月"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "年"
