l_russian:
 SETTING_DEBUG_SAVES: "Количество сохранений отладки"
 SETTING_TUTORIAL: "Обучение"
 SETTING_DISABLED_HINTS: "Отключенные подсказки"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Задержка подсказки"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nЗадержка между появлением всплывающих подсказок."
 SETTING_TOOLTIP_UNLOCK_TIME: "Задержка разблокировки"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nЗадержка перед разблокировкой всплывающих подсказок."
 SETTING_TOOLTIP_LOCK_TIME: "Задержка блокировки"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nЗадержка перед блокировкой всплывающих подсказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Задержка открытия"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nЗадержка перед блокировкой всплывающих подсказок, если одна подсказка уже открыта."
 #Audio
 SETTING_Sound_Effects: "Все звуковые эффекты"
 SETTING_Sound_Effects_TOOLTIP: "#T Громкость звуковых эффектов\n#!Меняет громкость всех звуковых эффектов."
 SETTING_Ambience: "Окружение"
 SETTING_Ambience_TOOLTIP: "#T Громкость окружения\n#!Меняет громкость звуков окружающей среды."
 SETTING_TOOLTIP_MODE: "Режим всплывающих подсказок"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nСпособ фиксации всплывающих подсказок — для подсказок в подсказках."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Поведение мыши"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nВсплывающие подсказки автоматически фиксируются, пока вы не уберете с них курсор мыши."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Ручной блок"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nНажмите #V среднюю кнопку мыши#!, чтобы заблокировать или разблокировать подсказку."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Блок по таймеру"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nВсплывающие подсказки остаются на месте, если курсор мыши в течение короткого времени остается неподвижным. #weak (По умолчанию)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Разное"
 SETTINGS_CATEGORY_TOOLTIPS: "Всплывающие подсказки"
 SETTINGS_CATEGORY_SFX: "Особые звуковые эффекты"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Общие"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Управление картой"
 SETTINGS_CATEGORY_SAVE_GAMES: "Сохранение игры"
 SETTINGS_CATEGORY_LANGUAGE: "Язык"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Расширенные"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Расширенные — карта"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Расширенные — персонажи"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Портреты"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Колорит"
 SETTINGS_CATEGORY_MULTIPLAYER: "Сетевая игра"
 SETTINGS_CATEGORY_MAP: "Карта"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Показывать раны и язвы"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nОпределяет, будут ли на портретах персонажей появляться реалистичные раны и следы от болезней."
 SETTING_SHOW_NUDITY: "Показывать наготу"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nИзображение обнаженных персонажей."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Загружаемый контент"
 SETTING_SHOW_CONTENT_SOURCE: "Показывать DLC события"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nОпределяет, будет ли в событиях указываться, к какому дополнению они относятся."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Панорама при бездействии: монарший двор"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nЕсли этот параметр включен, камера во время бездействия плавно скользит по вашему монаршему двору.\n\nНе действует при отключенной анимации персонажей."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Анимированный переход камеры"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nЕсли этот параметр включен, камера плавно перемещается к новой точке.\n\nНе действует при отключенной анимации персонажей."
 NEVER: "Никогда"
 MONTHLY: "Каждый месяц"
 HALFYEAR: "Каждые 6 месяцев"
 YEARLY: "Каждый год"
 FIVE_YEAR: "Каждые 5 лет"
 SETTINGS_CATEGORY_TUTORIAL: "Обучение"
 SETTING_REACTIVE_TUTORIAL: "Показывать контекстные советы"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nВключите или отключите советы, реагирующие на то, как вы играете. Они пригодятся новым игрокам в Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Показывать предложения"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nВключите или отключите советы, которые будут появляться через регулярные промежутки времени. Такие подсказки пригодятся новым игрокам в Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Сбросить контекстные советы"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Начать контекстные советы заново#!\nКонтекстные советы, которые уже были показаны, появятся еще раз."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Сбросить контекстные советы"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Вы уверены, что хотите сбросить контекстные советы?"
 SETTING_ADVANCED_SHADERS: "Дополнительные эффекты шейдеров"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Дополнительные эффекты шейдеров\n#!Этот параметр включает дополнительные эффекты шейдеров.\n\nПри отключении производительность системы может вырасти, а качество визуальных эффектов (например прорисовка ландшафта и воды) понизится."
 SETTING_WINTER_PARTICLE_EFFECTS: "Зимний эффект частиц"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nОпределяет, будет ли показываться эффект частиц на определенных частых карты в зимнее время.\n\nОтключение настройки может повысить производительность"
 SETTING_RESET_CAMERA_ROTATION: "Сброс вращения камеры"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nОпределяет, должна ли камера автоматически возвращаться в стандартное положение после поворота игроком."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Наклон камеры при отдалении"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nОпределяет, должна ли камера возвращаться к стандартному наклону при отдалении."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Фоновые персонажи двора"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nОпределяет, должна ли 3D-сцена монаршего двора включать в себя менее значимых фоновых персонажей."
 SETTING_MAP_HIGHLIGHT: "Подсветка курсора на карте"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nОпределяет интенсивность подсветки курсора на карте"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Подсвечивать владык на карте"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nОпределяет, будет ли владыка выделен на карте при выборе державы"
 OPTION_ALWAYS: "Всегда"
 OPTION_TRIBUTARY_ONLY: "Только данники"
 BASED_ON_ZOOM_LEVEL: "Динамические"
 ALWAYS_HIDE: "Всегда скрывать"
 ALWAYS_SHOW: "Всегда показывать"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Береговые границы"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nЭтот параметр управляет отображением береговых границ державы.\n$BASED_ON_ZOOM_LEVEL$ скрывает их на подробной карте.\n\n$ALWAYS_SHOW$ или $ALWAYS_HIDE$ могут улучшить производительность, но границы не будут автоматически скрываться при приближении."
 SETTINGS_DISCARD_CHANGES: "Отменить изменения"
 SETTING_HUD_SKIN: "Вид интерфейса"
 hud_skin_auto: "Динамический"
 default: "Стандартный"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nЗадает визуальный стиль интерфейса — 2D-элементов главного окна игры.\n\nЕсли выбран вариант «$hud_skin_auto$», интерфейс будет меняться в зависимости от культуры, конфессии и столицы игрока."
 SETTING_RICH_PRESENCE: "Выраженное присутствие"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nПоказывает вашим друзьям информацию о текущей игровой сессии, если платформа поддерживает такую возможность."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Династические названия держав"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nНекоторые культуры будут называть первый титул по имени династии (пример: Аббасиды)."
 map_table_style_auto: "Динамический"
 map_table_style_western: "По умолчанию"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Стиль стола карты"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nОпределяет визуальный стиль стола с картой — карты и 3D-окружения при отдалении камеры.\n\nЕсли выбран вариант «$map_table_style_auto$», стиль стола будет определяться в зависимости от игрока и его персонажа."
 SETTINGS_CATEGORY_STYLING: "Стиль интерфейса"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Отображать поветрия"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nОпределяет отображение эффектов болезней на карте"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Отображение легенд"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nОпределяет отображение эффектов легенд на карте"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Подробные значки [Concept('raid', 'налетов')|E]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nДелает значки [Concept('raid', 'налета')|E] на карте упрощенными или подробными\n\n#I Удерживайте клавишу Alt, чтобы увидеть все владения с добычей, которые можно [Concept('raid', 'разграбить')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Подробные значки [Concept('barter', 'торга')|E]"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_BARTER_MAP_ICON$#!\nДелает значки [Concept('barter', 'торговли')|E] на карте упрощенными или подробными\n\n#I Удерживайте клавишу Alt, чтобы увидеть все владения с добычей, в которых можно [Concept('barter', 'торговать')|E].#!"
 SETTING_PAPER_MAP_STYLE: "Стиль бумажной карты"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nОпределяет внешний вид карты при отдалении камеры.\n\nЕсли выбран $paper_map_style_auto|l$, бумажная карта будет соответствовать настройке «$SETTING_MAP_TABLE_STYLE$»."
 paper_map_style_auto: "Динамический"
 paper_map_style_western: "По умолчанию"
 paper_map_style_tgp: "All Under Heaven"
 SETTING_ADAPTIVE_FRAMERATE: "Адаптивная частота кадров"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Снижает частоту обновления экрана при снижении скорости обновления игры, чтобы улучшить производительность."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Тени от облаков"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nОпределяет, должны ли тени отображаться на местности."
 SETTING_HAS_TREE_DITHERING_ENABLED: "Сглаживание деревьев"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nОпределяет, должны ли эффекты сглаживания применяться к деревьям для более мягких краёв."
 SETTING_MAP_BRIGHTNESS: "Яркость бумажной карты"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nОпределяет интенсивность яркости бумажной карты"
