l_japanese:
 SETTING_DEBUG_SAVES: "デバッグセーブ数"
 SETTING_TUTORIAL: "チュートリアル"
 SETTING_DISABLED_HINTS: "ヒントを無効化"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "ツールチップの遅延"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nツールチップが表示されるまでの時間を設定します。"
 SETTING_TOOLTIP_UNLOCK_TIME: "固定解除の遅延"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nツールチップの固定が解除されるまでの時間を設定します。"
 SETTING_TOOLTIP_LOCK_TIME: "固定時の遅延"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nツールチップが固定されるまでの時間を設定します。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "画面を開いているときの遅延"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n別のツールチップをすでに開いている時に、ツールチップが固定されるまでの時間を設定します。"
 #Audio
 SETTING_Sound_Effects: "全てのサウンドエフェクト"
 SETTING_Sound_Effects_TOOLTIP: "#T サウンドエフェクトの音量\n#!すべての効果音の音量を設定します。"
 SETTING_Ambience: "環境音"
 SETTING_Ambience_TOOLTIP: "#T 環境音の音量\n#!環境音の音量を設定します。"
 SETTING_TOOLTIP_MODE: "ツールチップモード"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nツールチップの固定方法を設定し、ツールチップインツールチップを可能にします。"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "マウステンデンシー"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nカーソルが離れるまで自動的にツールチップが固定されます。"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "アクションロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\n#V ホイールクリック#! でツールチップの固定・固定解除を行います。"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "タイマーロック"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nカーソルをしばらく動かさずにいると、ツールチップがその場所に固定されます。#weak （初期設定）#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "その他"
 SETTINGS_CATEGORY_TOOLTIPS: "ツールチップ"
 SETTINGS_CATEGORY_SFX: "特定のサウンドエフェクト"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "一般"
 SETTINGS_CATEGORY_MAP_CONTROLS: "マップの操作"
 SETTINGS_CATEGORY_SAVE_GAMES: "セーブデータ"
 SETTINGS_CATEGORY_LANGUAGE: "言語"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "詳細設定"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "詳細設定 – マップ"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "詳細設定 – キャラクター"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "ポートレート"
 SETTINGS_CATEGORY_GAME_FLAVOR: "フレーバー"
 SETTINGS_CATEGORY_MULTIPLAYER: "マルチプレイ"
 SETTINGS_CATEGORY_MAP: "マップ"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "病気や怪我のグラフィック表示"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\n病気や怪我のグラフィックをキャラクターのポートレートに表示するかどうかを設定します。"
 SETTING_SHOW_NUDITY: "裸体を表示"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nキャラクターが裸体で表示されるかどうかを設定します。"
 SETTINGS_CATEGORY_GAME_DLC_MODS: "ダウンロードコンテンツ"
 SETTING_SHOW_CONTENT_SOURCE: "イベントのDLCを表示"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nどのDLCのイベントであるかを表示します。"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "王宮における無操作時のカメラ移動"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\n無操作時に王宮内をカメラがゆっくりと移動するかどうかを決定します。\n\nキャラクターアニメーションが無効の場合、この設定は無視されます。"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "王宮内の滑らかな場面転換"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\n王宮内においてカメラが次の場面に滑らかに移動するかどうかを決定します。\n\nキャラクターアニメーションが無効の場合、この設定は無視されます。"
 NEVER: "しない"
 MONTHLY: "毎月"
 HALFYEAR: "半年ごと"
 YEARLY: "毎年"
 FIVE_YEAR: "5年ごと"
 SETTINGS_CATEGORY_TUTORIAL: "チュートリアル"
 SETTING_REACTIVE_TUTORIAL: "リアルタイムヒントの表示"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nプレイ中にチュートリアルヒントを表示するかどうかを設定します。『Crusader Kings III』を初めてプレイする方におすすめの設定です。"
 SETTING_SHOW_SUGGESTIONS: "提案の表示"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nプレイ中、なにかを行うよう定期的に提案してもらうかどうかを設定します。『Crusader Kings III』を初めてプレイする方におすすめの設定です。"
 RESET_REACTIVE_ADVICE: "リアルタイムヒントのリセット"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T リアルタイムヒントのリセット#!\n過去に表示されたことのあるリアルタイムヒントが再度表示されるようになります。"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "リアルタイムヒントのリセット"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "リアルタイムヒントをリセットしますか？"
 SETTING_ADVANCED_SHADERS: "高度なシェーダー効果"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T 高度なシェーダー効果\n#!高度なシェーダー効果を有効にします。\n\nオフにすると、パフォーマンスが向上するかわりに一部のグラフィック（地形や水など）の質感が低下する可能性があります。"
 SETTING_WINTER_PARTICLE_EFFECTS: "雪片の効果"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nマップ内の一部地域において「冬」の効果が発生している場合に、雪片の効果を表示するかどうかを決定します。\n\nオフにすると、パフォーマンスが向上することがあります。"
 SETTING_RESET_CAMERA_ROTATION: "カメラ回転のリセット"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nカメラを回転した後に自動的に元の位置リセットするかどうかを決めます。"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "ズームアウト時にカメラをチルト"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nズームアウト時に元の角度になるようカメラをチルトするかどうかを決めます。"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "王宮の背景キャラクター"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\n王宮の3Dシーンにおいて、重要ではないキャラクターを表示させるかどうかを決定します。"
 SETTING_MAP_HIGHLIGHT: "マップカーソルのハイライト"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nマップ上のカーソルに適用されるハイライトの強度を決定します。"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "マップ上での大君主のハイライト"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\n領国の選択時に、その領国の大君主をハイライト表示する条件を決定します。"
 OPTION_ALWAYS: "常時"
 OPTION_TRIBUTARY_ONLY: "諸侯のみ"
 BASED_ON_ZOOM_LEVEL: "自動"
 ALWAYS_HIDE: "常に非表示"
 ALWAYS_SHOW: "常に表示"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "沿岸部の国境線"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\n沿岸部の国境線を表示するかどうかを設定します。\n$BASED_ON_ZOOM_LEVEL$に設定すると、ズームアップした際に国境線が非表示になります。\n\n$ALWAYS_SHOW$または$ALWAYS_HIDE$に設定すると、パフォーマンスが向上する可能性がありますが、ズームレベルに応じて国境線の表示/非表示を自動調整することはできなくなります。"
 SETTINGS_DISCARD_CHANGES: "変更を破棄"
 SETTING_HUD_SKIN: "HUDスキン"
 hud_skin_auto: "ダイナミック"
 default: "デフォルト"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nHUDインターフェース、すなわちメインゲーム画面に表示される2DのUIの視覚テーマを設定します。\n\n$hud_skin_auto$が選択されていると、HUDはプレイヤーの文化、宗派、領国の首都に応じて変化します。"
 SETTING_RICH_PRESENCE: "強い存在感"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nあなたの現在のプレイセッションの情報をフレンドが見れるようにします。ただし、あなたのプラットフォームがこの機能をサポートしている場合に限ります。"
 SETTING_USE_DYNASTY_NAMED_REALMS: "王朝の名を持つ領国"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\n一部の文化においては、主要称号が王朝に由来するものとなります（例: アッバース）。"
 map_table_style_auto: "ダイナミック"
 map_table_style_western: "デフォルト"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "マップテーブルのスタイル"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nマップテーブル、すなわちマップとズームアウト時に表示される3Dの周辺の様子の視覚スタイルを設定します。\n\n$map_table_style_auto$が選択されていると、マップテーブルのスタイルは現在のプレイヤーとキャラクターに応じて選択されます。"
 SETTINGS_CATEGORY_STYLING: "インターフェースのスタイル設定"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "疫病のグラフィック"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\n疫病の影響をマップ上に表示するかどうかを設定します。"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "伝説のグラフィック"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\n伝説の影響をマップ上に表示するかどうかを設定します。"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "詳細な[raid|E]アイコン"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\n[raid|E]のマップアイコンをシンプルにするか、詳細なアイコンにするかを設定します。\n\n#I 有効にすると、Altキーを長押しすれば[raid|E]可能な戦利品のあるすべての領分が表示されます。#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "詳細な[barter|E]アイコン"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\n[barter|E]のマップアイコンをシンプルにするか、詳細なアイコンにするかを設定します。\n\n#I 有効にすると、Altキーを長押しすれば[barter|E]可能な戦利品のあるすべての領分が表示されます。#!"
 SETTING_PAPER_MAP_STYLE: "紙マップのスタイル"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nマップを縮小したときに表示されるマップのスタイルを設定します。\n\n$paper_map_style_auto$が選択されている場合、紙マップには「$SETTING_MAP_TABLE_STYLE$」で使用されているスタイルが適用されます。"
 paper_map_style_auto: "ダイナミック"
 paper_map_style_western: "デフォルト"
 paper_map_style_tgp: "天上"
 SETTING_ADAPTIVE_FRAMERATE: "適応型フレームレート"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#! ゲームの更新速度が低下した場合に画面の更新頻度を下げ、プレイのパフォーマンスを改善します。"
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "雲の影"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\n雲の影のエフェクトを地形上に表示するかどうかを設定します。"
 SETTING_HAS_TREE_DITHERING_ENABLED: "木のディザリング"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nディザリング効果を適用して樹木の輪郭を滑らかにするかどうかを設定します。"
 SETTING_MAP_BRIGHTNESS: "紙マップの明るさ"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\n紙マップの明るさを決定します"
