l_simp_chinese:
 is_your_child_desc: "是你的孩子"
 is_your_close_family_desc: "是你的至亲"
 is_your_house_desc: "属于你的家族"
 landed_spouse_desc: "拥有有地配偶"
 landed_heir_desc: "拥有有地继承人"
 has_many_good_relations_desc: "拥有许多朋友"
 has_many_bad_relations_desc: "被仇敌包围"
 part_of_feud_desc: "世仇的一部分"
 high_diplomacy_desc: "拥有高外交能力"
 high_martial_desc: "拥有高军事能力"
 high_stewardship_desc: "拥有高管理能力"
 high_intrigue_desc: "拥有高谋略能力"
 high_learning_desc: "拥有高学识能力"
 high_prowess_desc: "拥有高勇武能力"
 high_education_desc: "受过高等教育"
 more_beautiful_desc: "比继承人更美丽"
 more_smart_desc: "比继承人更聪明"
 more_fit_desc: "比继承人更健康"
 more_strong_desc: "比继承人更强壮"
 more_skillful_desc: "比继承人更有能力"
 has_nickname_desc: "拥有称号"
 more_famous_desc: "比继承人更知名"
 second_in_line_desc: "继承第二顺位"
 higher_title_desc: "持有更高头衔"
 new_liege_desc: "会处于新领主之下"
 new_top_liege_desc: "会处于新最高领主之下"
 tall_claims_desc: "持有重要宣称"
 pressed_claims_desc: "持有强宣称"
 unpressed_claims_desc: "持有弱宣称"
 inheritance_line_desc: "处于继承顺位中"
 has_interesting_story_desc: "拥有有趣的故事"
 child_of_destiny_desc: "是天选之子"
 virtues_interesting_desc: "拥有美德特质"
 tourney_xp_desc: "经验丰富的[GetTrait('tourney_participant').GetName( GetNullCharacter )]"
 reveler_xp_desc: "经验丰富的[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )]"
 mystic_xp_desc: "经验丰富的[GetTrait('lifestyle_mystic').GetName( GetNullCharacter )]"
 hunter_xp_desc: "经验丰富的[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )]"
 blademaster_xp_desc: "经验丰富的[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )]"
 traveler_xp_desc: "经验丰富的[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )]"
 physician_xp_desc: "经验丰富的[GetTrait('lifestyle_physician').GetName( GetNullCharacter )]"
 herbalist_xp_desc: "经验丰富的[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )]"
 loyal_interesting_desc: "[GetTrait('loyal').GetName( GetNullCharacter )]"
 disloyal_interesting_desc: "[GetTrait('disloyal').GetName( GetNullCharacter )]"
 faith_warrior_interesting_desc: "是[GetTrait('faith_warrior').GetName( GetNullCharacter )]"
 blood_of_prophet_interesting_desc: "拥有[GetTrait('blood_of_prophet').GetName( GetNullCharacter )]特质"
 varangian_interesting_desc: "是[GetTrait('varangian').GetName( GetNullCharacter )]"
 poet_interesting_desc: "是[GetTrait('lifestyle_poet').GetName( GetNullCharacter )]"
 peasant_leader_interesting_desc: "是[GetTrait('peasant_leader').GetName( GetNullCharacter )]"
 populist_leader_interesting_desc: "是[GetTrait('populist_leader').GetName( GetNullCharacter )]"
 berserker_interesting_desc: "是[GetTrait('berserker').GetName( GetNullCharacter )]"
 born_in_the_purple_interesting_desc: "[GetTrait('born_in_the_purple').GetName( GetNullCharacter )]"
 scaly_interesting_desc: "有[GetTrait('scaly').GetName( GetNullCharacter )]"
 albino_interesting_desc: "有[GetTrait('albino').GetName( GetNullCharacter )]"
 dwarf_interesting_desc: "是[GetTrait('dwarf').GetName( GetNullCharacter )]"
 giant_interesting_desc: "是[GetTrait('giant').GetName( GetNullCharacter )]"
 devoted_interesting_desc: "是[GetTrait('devoted').GetName( GetNullCharacter )]"
 pure_blooded_interesting_desc: "是[GetTrait('pure_blooded').GetName( GetNullCharacter )]"
 crusader_king_interesting_desc: "是[GetTrait('crusader_king').GetName( GetNullCharacter )]"
 disinherited_interesting_desc: "[GetTrait('disinherited').GetName( GetNullCharacter )]"
 blind_interesting_desc: "[GetTrait('blind').GetName( GetNullCharacter )]"
 is_diarch_interesting_desc: "是共治者"
 ruler_in_foreign_lands_interesting_desc: "是境外领土的统治者"
 valiant_knight_interesting_desc: "是侠义骑士"
 sinful_bastard_interesting_desc: "是罪恶的[GetTrait('bastard').GetName( GetNullCharacter )]"
 adventurer_interesting_desc: "是冒险者"
 liege_crusader_king_liege_lineage_interesting_desc: "[GetTrait('crusader_king').GetName( GetNullCharacter )]世系的领主"
 holy_site_steward_interesting_desc: "首府是圣地"
 has_a_legend_interesting_desc: "拥有传奇"
 weak_hook_liege_interesting_desc: "拥有对领主的弱牵制"
 strong_hook_liege_interesting_desc: "拥有对领主的强牵制"
 beloved_by_pope_interesting_desc: "受教宗青睐"
 head_of_faith_interesting_desc: "是信仰领袖"
 stronger_than_liege_interesting_desc: "比领主更强"
 small_king_interesting_desc: "是较小王国统治者"
 can_feudalize_interesting_desc: "可以封建化"
 multiduke_interesting_desc: "持有许多公国"
 legitimacy_interesting_desc: "极其正统的统治者"
 non_dominant_gender_ambitious_char_interesting_desc: "是野心勃勃的非主导性别角色"
 non_dominant_gender_ruler_interesting_desc: "是非主导性别的统治者"
 treacherous_schemer_interesting_desc: "是狡诈的阴谋家"
 kind_hearted_diplomat_interesting_desc: "是心善的外交家"
 different_faith_interesting_desc: "信仰不同"
 greedy_steward_interesting_desc: "是贪婪的管理者"
 brazen_commander_interesting_desc: "是无耻的将领"
 pious_theologian_interesting_desc: "是虔诚的神学家"
 salacious_seducer_interesting_desc: "是淫荡的勾引者"
 high_skills_desc: "能力非常高"
 killed_a_lot_interesting_desc: "杀死超过10人"
 has_both_good_and_bad_genetics_desc: "拥有正面和负面可遗传特质"
 good_genetics_desc: "正面可遗传特质"
 bad_genetics_desc: "负面可遗传特质"
 holds_rome_interesting_desc: "持有[GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "持有[GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "持有[GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "持有[GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "持有[GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "控制特殊建筑"
 has_historical_artifacts_interesting_desc: "拥有独有历史宝物"
 underrepresented_faith_interesting_desc: "属于代表性不足的信仰"
 underrepresented_culture_interesting_desc: "属于代表性不足的文化"
 outside_realm_desc: "独立统治者"
 knows_many_secrets_interesting_desc: "知道许多秘密"
 has_secrets_interesting_desc: "拥有秘密"
 extremely_wealthy_interesting_desc: "非常富有"
 landless_heir_uninteresting_desc: "无领地的头衔继承人"
 three_virtues_desc: "拥有三种美德"
 three_sins_desc: "拥有三种罪恶"
 skills_difficulty: "来自能力"
 legitimacy_difficulty: "来自正统性"
 virtuous_traits_difficulty: "拥有美德特质"
 physique_good_3_difficulty: "[GetTrait('physique_good_3').GetName( GetNullCharacter )]"
 physique_good_2_difficulty: "[GetTrait('physique_good_2').GetName( GetNullCharacter )]"
 physique_good_1_difficulty: "[GetTrait('physique_good_1').GetName( GetNullCharacter )]"
 intellect_good_3_difficulty: "[GetTrait('intellect_good_3').GetName( GetNullCharacter )]"
 intellect_good_2_difficulty: "[GetTrait('intellect_good_2').GetName( GetNullCharacter )]"
 intellect_good_1_difficulty: "[GetTrait('intellect_good_1').GetName( GetNullCharacter )]"
 beauty_good_3_difficulty: "[GetTrait('beauty_good_3').GetName( GetNullCharacter )]"
 beauty_good_2_difficulty: "[GetTrait('beauty_good_2').GetName( GetNullCharacter )]"
 beauty_good_1_difficulty: "[GetTrait('beauty_good_1').GetName( GetNullCharacter )]"
 shrewd_difficulty: "[GetTrait('shrewd').GetName( GetNullCharacter )]"
 strong_difficulty: "[GetTrait('strong').GetName( GetNullCharacter )]"
 sinful_traits_difficulty: "拥有罪恶特质"
 incapable_difficulty: "[GetTrait('incapable').GetName( GetNullCharacter )]"
 leper_difficulty: "有[GetTrait('leper').GetName( GetNullCharacter )]"
 maimed_difficulty: "[GetTrait('maimed').GetName( GetNullCharacter )]"
 inbred_difficulty: "[GetTrait('inbred').GetName( GetNullCharacter )]"
 severely_wounded_difficulty: "受了重伤"
 disinherited_difficulty: "[GetTrait('disinherited').GetName( GetNullCharacter )]"
 sickly_difficulty: "[GetTrait('sickly').GetName( GetNullCharacter )]"
 poxed_difficulty: "有[GetTrait('great_pox').GetName( GetNullCharacter )]"
 blind_difficulty: "[GetTrait('blind').GetName( GetNullCharacter )]"
 infirm_difficulty: "[GetTrait('infirm').GetName( GetNullCharacter )]"
 eunuch_difficulty: "是[GetTrait('eunuch_1').GetName( GetNullCharacter )]"
 lunatic_difficulty: "[GetTrait('lunatic').GetName( GetNullCharacter )]"
 murderer_difficulty: "是[GetTrait('murderer').GetName( GetNullCharacter )]"
 excommunicated_difficulty: "被绝罚"
 bleeder_difficulty: "[GetTrait('bleeder').GetName( GetNullCharacter )]"
 physique_bad_3_difficulty: "[GetTrait('physique_bad_3').GetName( GetNullCharacter )]"
 physique_bad_2_difficulty: "[GetTrait('physique_bad_2').GetName( GetNullCharacter )]"
 physique_bad_1_difficulty: "[GetTrait('physique_bad_1').GetName( GetNullCharacter )]"
 intellect_bad_3_difficulty: "[GetTrait('intellect_bad_3').GetName( GetNullCharacter )]"
 intellect_bad_2_difficulty: "[GetTrait('intellect_bad_2').GetName( GetNullCharacter )]"
 intellect_bad_1_difficulty: "[GetTrait('intellect_bad_1').GetName( GetNullCharacter )]"
 beauty_bad_3_difficulty: "[GetTrait('beauty_bad_3').GetName( GetNullCharacter )]"
 beauty_bad_2_difficulty: "[GetTrait('beauty_bad_2').GetName( GetNullCharacter )]"
 beauty_bad_1_difficulty: "[GetTrait('beauty_bad_1').GetName( GetNullCharacter )]"
 dull_difficulty: "[GetTrait('dull').GetName( GetNullCharacter )]"
 weak_difficulty: "[GetTrait('weak').GetName( GetNullCharacter )]"
 sodomite_difficulty: "是[GetTrait('sodomite').GetName( GetNullCharacter )]"
 incestuous_difficulty: "[GetTrait('incestuous').GetName( GetNullCharacter )]"
 fornicator_difficulty: "是[GetTrait('fornicator').GetName( GetNullCharacter )]"
 adulterer_difficulty: "是[GetTrait('adulterer').GetName( GetNullCharacter )]"
 cannibal_difficulty: "是[GetTrait('cannibal').GetName( GetNullCharacter )]"
 witch_difficulty: "是[GetTrait('witch').GetName( GetNullCharacter )]"
 kinslayer_difficulty: "是[GetTrait('kinslayer_1').GetName( GetNullCharacter )]"
 flagellant_difficulty: "是[GetTrait('flagellant').GetName( GetNullCharacter )]"
 improvident_difficulty: "[GetTrait('improvident').GetName( GetNullCharacter )]"
 profligate_difficulty: "[GetTrait('profligate').GetName( GetNullCharacter )]"
 disfigured_difficulty: "[GetTrait('disfigured').GetName( GetNullCharacter )]"
 drunkard_difficulty: "是[GetTrait('drunkard').GetName( GetNullCharacter )]"
 possessed_difficulty: "[GetTrait('possessed').GetName( GetNullCharacter )]"
 depressed_difficulty: "[GetTrait('depressed').GetName( GetNullCharacter )]"
 infertile_difficulty: "[GetTrait('infertile').GetName( GetNullCharacter )]"
 spindly_difficulty: "[GetTrait('spindly').GetName( GetNullCharacter )]"
 paranoid_difficulty: "[GetTrait('paranoid').GetName( GetNullCharacter )]"
 gout_difficulty: "有[GetTrait('gout_ridden').GetName( GetNullCharacter )]"
 wheezing_difficulty: "[GetTrait('wheezing').GetName( GetNullCharacter )]"
 craven_difficulty: "[GetTrait('craven').GetName( GetNullCharacter )]"
 shy_difficulty: "[GetTrait('shy').GetName( GetNullCharacter )]"
 decadent_difficulty: "[GetTrait('decadent').GetName( GetNullCharacter )]"
 denounced_difficulty: "[GetTrait('denounced').GetName( GetNullCharacter )]"
 bastard_difficulty: "是[GetTrait('bastard').GetName( GetNullCharacter )]"
 weak_heritage_difficulty: "拥有弱小的传承"
 comfort_eater_difficulty: "是[GetTrait('comfort_eater').GetName( GetNullCharacter )]"
 inappetetic_difficulty: "[GetTrait('inappetetic').GetName( GetNullCharacter )]"
 reclusive_difficulty: "[GetTrait('reclusive').GetName( GetNullCharacter )]"
 irritable_difficulty: "[GetTrait('irritable').GetName( GetNullCharacter )]"
 rakish_difficulty: "[GetTrait('rakish').GetName( GetNullCharacter )]"
 hashishiyah_difficulty: "是[GetTrait('hashishiyah').GetName( GetNullCharacter )]"
 celibate_difficulty: "[GetTrait('celibate').GetName( GetNullCharacter )]"
 lovers_pox_difficulty: "有[GetTrait('lovers_pox').GetName( GetNullCharacter )]"
 wounded_difficulty: "[GetTrait('wounded_1').GetName( GetNullCharacter )]"
 albino_difficulty: "[GetTrait('albino').GetName( GetNullCharacter )]"
 lisping_difficulty: "[GetTrait('lisping').GetName( GetNullCharacter )]"
 stuttering_difficulty: "[GetTrait('stuttering').GetName( GetNullCharacter )]"
 giant_difficulty: "是[GetTrait('giant').GetName( GetNullCharacter )]"
 scaly_difficulty: "[GetTrait('scaly').GetName( GetNullCharacter )]"
 clubfooted_difficulty: "[GetTrait('clubfooted').GetName( GetNullCharacter )]"
 dwarf_difficulty: "是[GetTrait('dwarf').GetName( GetNullCharacter )]"
 hunchbacked_difficulty: "[GetTrait('hunchbacked').GetName( GetNullCharacter )]"
 lazy_difficulty: "[GetTrait('lazy').GetName( GetNullCharacter )]"
 gluttonous_difficulty: "[GetTrait('gluttonous').GetName( GetNullCharacter )]"
 deviant_difficulty: "是[GetTrait('deviant').GetName( GetNullCharacter )]"
 at_war_difficulty: "处于战争"
 losing_war_difficulty: "战争不利"
 faction_difficulty: "强大派系的目标"
 powerful_neighbors_difficulty: "强大的相邻统治者"
 military_difficulty: "军力"
 rivals_difficulty: "有仇敌"
 primary_heir_wrong_dynasty_difficulty: "第一继承人来自错误宗族"
 children_wrong_dynasty_difficulty: "孩子属于错误宗族"
 hostile_faith_liege_difficulty: "敌对信仰的领主"
 nonpreferred_gender_difficulty: "信仰中的非优先性别"
 wrong_lineality_difficulty: "婚姻中的错误血系"
 stress_level_difficulty: "高压力等级"
 gold_difficulty: "极多财富"
 debt_level_difficulty: "高债务等级"
 is_ill_difficulty: "患有衰弱性疾病"
 imprisoned_difficulty: "被囚禁"
 elder_difficulty: "高龄"
 poor_health_difficulty: "健康不佳"
 is_a_vassal_difficulty: "是封臣"
 non_adult_difficulty: "儿童"
 weak_domain_difficulty: "弱小的直辖"
 unlanded_difficulty: "未持有头衔"
 character_difficulty_text: "难度：[Character.Custom('CharacterDifficulty')]"
 character_difficulty_breakdown_header: "难度明细"
 choose_destiny_header_text: "选择新天命"
 will_become_adventurer: "会成为[GetGovernment('landless_adventurer_government').GetName]"
 character_interest_breakdown_header: "有趣的部分"
 different_government_desc: "政体不同"
 opposite_struggle_faction_desc: "斗争中的反对派"
