l_polish:
 SETTING_DEBUG_SAVES: "Liczba debugowanych zapisów"
 SETTING_TUTORIAL: "Samouczek"
 SETTING_DISABLED_HINTS: "Wyłączone wskazówki"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Opóźnienie podpowiedzi"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nUstala opóźnienie pojawiania się podpowiedzi."
 SETTING_TOOLTIP_UNLOCK_TIME: "Znikanie podpowiedzi"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nOkreśla czas, po którym zablokowana podpowiedź zniknie."
 SETTING_TOOLTIP_LOCK_TIME: "Opóźnienie blokady podpowiedzi"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nUstala opóźnienie zablokowania podpowiedzi."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Znikanie wewnętrznych podpowiedzi"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nUstala czas, po którym zablokowana podpowiedź wyświetlona w innej zablokowanej podpowiedzi, zniknie."
 #Audio
 SETTING_Sound_Effects: "Wszystkie efekty dźwiękowe"
 SETTING_Sound_Effects_TOOLTIP: "#T Głośność efektów dźwiękowych\n#!Określa głośność WSZYSTKICH efektów dźwiękowych."
 SETTING_Ambience: "Otoczenie"
 SETTING_Ambience_TOOLTIP: "#T Głośność otoczenia\n#!Określa poziom głośności efektów otoczenia."
 SETTING_TOOLTIP_MODE: "Tryb podpowiedzi"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nUstawia sposób, w jaki podpowiedzi „blokują się”, umożliwiając wyświetlanie podpowiedzi w podpowiedziach."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Obecność myszy"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nPodpowiedź automatycznie zablokuje się, dopóki kursor obecny jest jej obszarze."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Blokada akcją"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nNaciśnij #V środkowy przycisk myszy#!, aby zablokować i odblokować podpowiedź."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Blokada czasowa"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nPodpowiedź zablokuje się, jeśli kursor będzie obecny na jej obszarze przez krótką chwilę. #weak (Ustawienie domyślne)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Różne"
 SETTINGS_CATEGORY_TOOLTIPS: "Podpowiedzi"
 SETTINGS_CATEGORY_SFX: "Efekty dźwiękowe"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Ogólne"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Kontrola mapy"
 SETTINGS_CATEGORY_SAVE_GAMES: "Zapisane gry"
 SETTINGS_CATEGORY_LANGUAGE: "Język"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Zaawansowane – Ogólne"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Zaawansowane – Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Zaawansowane – Postacie"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portrety"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Rozmaitość"
 SETTINGS_CATEGORY_MULTIPLAYER: "Tryb wieloosobowy"
 SETTINGS_CATEGORY_MAP: "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Pokazuj choroby i urazy na portretach"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nOkreśla, czy urazy i choroby będą widoczne na portretach postaci."
 SETTING_SHOW_NUDITY: "Pokazuj nagość"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nOkreśla, czy postacie mogą być pokazywane nago."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Zawartość do pobrania"
 SETTING_SHOW_CONTENT_SOURCE: "Pokazuj DLC wydarzenia"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nOkreśla, czy wydarzenia mają pokazywać, z którego DLC pochodzą."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Dwór monarszy: ruch kamery"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nJeśli ta opcja jest włączona, kamera na dworze monarszym będzie łagodnie się poruszać w stanie bezczynności.\n\nNie działa, gdy opcja „animowane postacie” jest wyłączona."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Dwór monarszy: płynne przejścia"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nOkreśla czy kamera na dworze monarszym ma płynnie przemieszczać się w nowe miejsce.\n\nJeżeli animowane postacie są wyłączone, to ustawienie nie wywołuje żadnego efektu."
 NEVER: "Nigdy"
 MONTHLY: "Co miesiąc"
 HALFYEAR: "Co 6 miesięcy"
 YEARLY: "Co roku"
 FIVE_YEAR: "Co 5 lat"
 SETTINGS_CATEGORY_TUTORIAL: "Samouczek"
 SETTING_REACTIVE_TUTORIAL: "Pokazuj reaktywną poradę"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nUstawia, czy gra będzie wyświetlała porady w stylu samouczka w reakcji na twoje działania. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Pokazuj sugestie"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nUstawia, czy gra ma wyświetlać sugestie w określonych odstępach czasu. Przydatne dla graczy, którzy nie mają doświadczenia z Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Zresetuj reaktywną poradę#!\nWcześniej widziane porady reaktywne pojawią się ponownie."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Zresetuj reaktywną poradę"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Czy na pewno chcesz zresetować reaktywną poradę?"
 SETTING_ADVANCED_SHADERS: "Zaawansowane efekty shaderów"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Zaawansowane efekty shaderów#!\nTa opcja włącza zaawansowane efekty shaderów.\n\nWyłączenie tej opcji może zwiększyć wydajność kosztem pogorszenia wyglądu niektórych efektów (np. terenu i wody)"
 SETTING_WINTER_PARTICLE_EFFECTS: "Efekty cząsteczkowe zimy"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nOkreśla, czy efekty cząsteczkowe będą wyświetlane na niektórych obszarach mapy w okresie zimy.\n\nWyłączenie tej opcji może zwiększyć wydajność"
 SETTING_RESET_CAMERA_ROTATION: "Resetowanie pozycji kamery"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nOkreśla, czy kamera ma automatycznie przywracać domyślne położenie po obróceniu jej przez użytkownika."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Pochylenie kamery przy oddalaniu"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nOkreśla, czy kamera powinna pochylać się w kierunku domyślnego pochylenia podczas oddalania."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Drugoplanowe postacie dworu"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T Drugoplanowe postacie dworu#!\nOkreśla, czy na scenie 3D dworu monarszego mają być wyświetlane mniej ważne postacie drugoplanowe."
 SETTING_MAP_HIGHLIGHT: "Podświetlenie kursora na mapie"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nOkreśla intensywność podświetlenia kursora na mapie"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Podświetlenie zwierzchnika na mapie"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nOkreśla sytuacje, w których przy wyborze państwa będzie podświetlony jego zwierzchnik."
 OPTION_ALWAYS: "Zawsze"
 OPTION_TRIBUTARY_ONLY: "Tylko trybutariusze"
 BASED_ON_ZOOM_LEVEL: "Dynamiczne"
 ALWAYS_HIDE: "Zawsze ukryte"
 ALWAYS_SHOW: "Zawsze widoczne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Granice przybrzeżne"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nTa opcja pozwoli kontrolować, kiedy powinny zostać pokazane granice morskie.\nJeśli ustawienie jest $BASED_ON_ZOOM_LEVEL$, zostaną one ukryte w przybliżeniu.\n\nWybranie $ALWAYS_SHOW$ lub $ALWAYS_HIDE$ może zwiększyć wydajność kosztem dynamicznego pojawiania granic przybrzeżnych."
 SETTINGS_DISCARD_CHANGES: "Odrzuć zmiany"
 SETTING_HUD_SKIN: "Skórka interfejsu"
 hud_skin_auto: "Dynamiczny"
 default: "Domyślna"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nUstawia styl wizualny interfejsu – elementów 2D głównego okna gry.\n\nJeśli wybrano dynamiczny, interfejs zmieni się w zależności od kultury, wiary i stolicy państwa gracza."
 SETTING_RICH_PRESENCE: "Status w czasie rzeczywistym"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nWyświetla znajomym informacje o bieżącej sesji gry, jeśli platforma obsługuje tę funkcję."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Dynastia jako nazwa państwa"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nNiektóre kultury będą nazywać swój główny tytuł po swojej dynastii (np.: Abbasydzi)."
 map_table_style_auto: "Dynamiczny"
 map_table_style_western: "Domyślny"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Styl stołu z mapą"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nOkreśla styl wizualny stołu z mapą – mapę i środowisko 3D wyświetlane po oddaleniu.\n\nJeśli wybrano dynamiczną, styl stołu mapy zostanie wybrany na podstawie bieżącego gracza i jego postaci."
 SETTINGS_CATEGORY_STYLING: "Stylizacja interfejsu"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Grafiki chorób"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nOkreśla, czy na mapie mają być wyświetlane efekty chorób"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Grafiki legend"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nOkreśla, czy na mapie mają być wyświetlane efekty legend"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Szczegółowe ikony [Concept('raid', 'najazdu')|E]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nDecyduje o tym, czy ikony na mapie [Concept('raid', 'najazdu')|E] mają być uproszczone, czy szczegółowe\n\n#I Przytrzymaj klawisz Alt, aby wyświetlić wszystkie posiadłości z łupami, które możesz [Concept('raid', 'najechać')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Szczegółowe ikony [barter|E]"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nDecyduje o tym, czy ikony na mapie [barter|E] mają być uproszczone, czy szczegółowe\n\n#I Przytrzymaj klawisz Alt, aby wyświetlić wszystkie posiadłości z łupami, w których możesz prowadzić [barter|E].#!"
 SETTING_PAPER_MAP_STYLE: "Styl mapy papierowej"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nUstawienie pozwala wybrać styl mapy po jej oddaleniu.\n\nJeśli wybrano styl dynamiczny, styl mapy papierowej będzie zgodny z ustawieniem „$SETTING_MAP_TABLE_STYLE$”."
 paper_map_style_auto: "Dynamiczny"
 paper_map_style_western: "Domyślny"
 paper_map_style_tgp: "All Under Heaven"
 SETTING_ADAPTIVE_FRAMERATE: "Adaptacyjna częstotliwość odświeżania"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Zmniejsza częstotliwość odświeżania ekranu, jeśli prędkość odświeżania gry spadnie, aby poprawić wydajność rozgrywki."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Cienie chmur"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nOkreśla, czy na terenie mają być wyświetlane efekty cieni chmur"
 SETTING_HAS_TREE_DITHERING_ENABLED: "Rozpraszanie drzew"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nOkreśla, czy do drzew mają być zastosowane efekty rozpraszania w celu wygładzania krawędzi"
 SETTING_MAP_BRIGHTNESS: "Jasność mapy papierowej"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_BRIGHTNESS$#!\nOkreśla intensywność jasności mapy papierowej"
